import type { FeedPost, Court, Player, Game } from '@/types/index';

export const FEED_DATA: FeedPost[] = [
  {
    id: 'post-001',
    type: 'play',
    author: { username: 'McKeyra', handle: '@mr_ballinthe6', avatarUrl: '', verified: true },
    imageUrl: '',
    caption: 'Ankle breaker into a stepback three at Pan Am. Defender is still looking for his shoes.',
    score: 342,
    assists: 87,
    timestamp: '2h ago',
  },
  {
    id: 'post-002',
    type: 'play',
    author: { username: 'CourtKing_99', handle: '@courtking_99', avatarUrl: '' },
    imageUrl: '',
    caption: "Full-court press break to a no-look dime. Scarborough runs don't stop.",
    score: 218,
    assists: 54,
    timestamp: '3h ago',
  },
  {
    id: 'post-003',
    type: 'play',
    author: { username: 'DunkCity', handle: '@dunkcity_to', avatarUrl: '' },
    imageUrl: '',
    caption: 'Caught a body at Cherry Beach. Poster of the summer right here.',
    score: 512,
    assists: 123,
    timestamp: '5h ago',
  },
  {
    id: 'post-004',
    type: 'game',
    teamA: { name: 'B.M.T. Titans', score: 78, logo: '', record: '12-2', color: 'from-orange-500 to-red-500' },
    teamB: { name: 'SJPII Panthers', score: 72, logo: '', record: '10-4', color: 'from-blue-500 to-indigo-500' },
    gameStatus: 'Final',
    venue: 'Pan Am Centre, Scarborough',
    mvp: { name: 'Caleb Smith', stats: '28 PTS \u00b7 6 REB \u00b7 3 AST', avatar: 'CS' },
    impactScore: 94,
  },
  {
    id: 'post-005',
    type: 'nobleed',
    author: { username: 'Scarborough Elite', handle: '@scarborough_elite', avatarUrl: '' },
    imageUrl: '',
    caption: "Open run at L'Amoreaux tonight. Pull up if you got game. No excuses.",
    score: 176,
    assists: 41,
    commentCount: 34,
    timestamp: '6h ago',
  },
  {
    id: 'post-006',
    type: 'nobleed',
    author: { username: 'SixMan', handle: '@sixman_hoops', avatarUrl: '' },
    imageUrl: '',
    caption: "Who's really the best point guard in the 6ix right now? Drop your top 5 below.",
    score: 289,
    assists: 96,
    commentCount: 78,
    timestamp: '8h ago',
  },
  {
    id: 'post-007',
    type: 'fullwidth',
    author: { username: 'Toronto Hoops', handle: '@toronto_hoops', avatarUrl: '', verified: true },
    imageUrl: '',
    caption: 'Summer league registrations are OPEN. 32 teams, 6 weeks, one champion. Link in bio.',
    score: 624,
    assists: 210,
    timestamp: '10h ago',
  },
  {
    id: 'post-008',
    type: 'headerfill',
    author: { username: 'Rexdale Runs', handle: '@rexdale_runs', avatarUrl: '' },
    imageUrl: '',
    caption: 'Midnight runs at Driftwood hit different. The energy out here is unmatched.',
    score: 198,
    assists: 63,
    drops: 47,
    timestamp: '12h ago',
  },
  {
    id: 'post-009',
    type: 'slider',
    author: { username: 'NorthSide Ballers', handle: '@northside_ball', avatarUrl: '' },
    imageUrls: ['', '', ''],
    caption: 'Downsview Park tournament recap. Three games, three wins. We came to dominate.',
    score: 445,
    assists: 134,
    drops: 62,
    timestamp: '1d ago',
  },
  {
    id: 'post-010',
    type: 'game',
    teamA: { name: 'Northside Kings', score: 91, logo: '', record: '11-3', color: 'from-emerald-500 to-cyan-500' },
    teamB: { name: 'East York Wolves', score: 84, logo: '', record: '9-5', color: 'from-gray-500 to-slate-600' },
    gameStatus: 'Final',
    venue: 'Downsview Park, North York',
    mvp: { name: 'Marcus Thompson', stats: '34 PTS \u00b7 8 AST \u00b7 5 STL', avatar: 'MT' },
    impactScore: 97,
  },
];

export const COURTS: Court[] = [
  { id: 'court-001', name: 'Pan Am Centre', area: 'Scarborough', address: '875 Morningside Ave, Scarborough, ON', type: 'indoor', courts: 6, activePlayers: 24, hot: true, imageUrl: '', rating: 4.8 },
  { id: 'court-002', name: 'Downsview Park', area: 'North York', address: '70 Canuck Ave, North York, ON', type: 'outdoor', courts: 4, activePlayers: 18, hot: true, imageUrl: '', rating: 4.5 },
  { id: 'court-003', name: 'Driftwood Community Centre', area: 'Jane & Finch', address: '4401 Jane St, Toronto, ON', type: 'indoor', courts: 2, activePlayers: 12, hot: false, imageUrl: '', rating: 4.3 },
  { id: 'court-004', name: "L'Amoreaux Sports Complex", area: 'Scarborough', address: '2000 McNicoll Ave, Scarborough, ON', type: 'indoor', courts: 3, activePlayers: 8, hot: false, imageUrl: '', rating: 4.6 },
  { id: 'court-005', name: 'Cherry Beach', area: 'Waterfront', address: '1 Cherry St, Toronto, ON', type: 'outdoor', courts: 2, activePlayers: 31, hot: true, imageUrl: '', rating: 4.2 },
  { id: 'court-006', name: 'Malvern Community Centre', area: 'Scarborough', address: '30 Sewells Rd, Scarborough, ON', type: 'outdoor', courts: 2, activePlayers: 6, hot: false, imageUrl: '', rating: 4.0 },
];

export const PLAYERS: Player[] = [
  { id: 'player-001', name: 'McKeyra', handle: '@mr_ballinthe6', avatar: 'MK', impactScore: 12400, assistsGiven: 842, playsPosted: 67, rank: 1, streak: 14, verified: true, color: 'from-purple-500 to-blue-500' },
  { id: 'player-002', name: 'Caleb Smith', handle: '@caleb_buckets', avatar: 'CS', impactScore: 11200, assistsGiven: 714, playsPosted: 58, rank: 2, streak: 9, verified: true, color: 'from-orange-500 to-red-500' },
  { id: 'player-003', name: 'Marcus Thompson', handle: '@marcust_6ix', avatar: 'MT', impactScore: 9800, assistsGiven: 623, playsPosted: 51, rank: 3, streak: 11, verified: true, color: 'from-emerald-500 to-cyan-500' },
  { id: 'player-004', name: 'DunkCity', handle: '@dunkcity_to', avatar: 'DC', impactScore: 8340, assistsGiven: 489, playsPosted: 44, rank: 4, streak: 7, verified: false, color: 'from-pink-500 to-purple-500' },
  { id: 'player-005', name: 'CourtKing_99', handle: '@courtking_99', avatar: 'CK', impactScore: 7120, assistsGiven: 392, playsPosted: 38, rank: 5, streak: 5, verified: false, color: 'from-yellow-500 to-orange-500' },
  { id: 'player-006', name: 'SixMan', handle: '@sixman_hoops', avatar: 'SM', impactScore: 6450, assistsGiven: 334, playsPosted: 31, rank: 6, streak: 3, verified: false, color: 'from-blue-500 to-indigo-500' },
  { id: 'player-007', name: 'Rexdale Runs', handle: '@rexdale_runs', avatar: 'RR', impactScore: 5890, assistsGiven: 278, playsPosted: 27, rank: 7, streak: 6, verified: false, color: 'from-red-500 to-rose-500' },
  { id: 'player-008', name: 'NorthSide Ball', handle: '@northside_ball', avatar: 'NB', impactScore: 5210, assistsGiven: 241, playsPosted: 23, rank: 8, streak: 2, verified: false, color: 'from-teal-500 to-green-500' },
];

export const GAMES: Game[] = [
  { id: 'game-001', level: 'pro', teamA: { name: 'B.M.T. Titans', score: 54, logo: '', record: '12-2', color: '#f97316' }, teamB: { name: 'Scarborough Elite', score: 48, logo: '', record: '8-6', color: '#64748b' }, status: 'live', venue: 'Pan Am Centre, Scarborough', time: 'Q3 4:22', mvp: { name: 'Caleb Smith', stats: '18 PTS \u00b7 4 REB \u00b7 2 AST', avatar: 'CS' }, impactScore: 88 },
  { id: 'game-002', level: 'pro', teamA: { name: 'Northside Kings', score: 67, logo: '', record: '11-3', color: '#10b981' }, teamB: { name: 'Rexdale Runs', score: 61, logo: '', record: '7-7', color: '#ef4444' }, status: 'live', venue: 'Downsview Park, North York', time: 'Q4 8:15', mvp: { name: 'Marcus Thompson', stats: '24 PTS \u00b7 7 AST \u00b7 3 STL', avatar: 'MT' }, impactScore: 92 },
  { id: 'game-003', level: 'pro', teamA: { name: 'East York Wolves', score: 0, logo: '', record: '9-5', color: '#6b7280' }, teamB: { name: 'SJPII Panthers', score: 0, logo: '', record: '10-4', color: '#3b82f6' }, status: 'upcoming', venue: "L'Amoreaux Sports Complex", time: 'Today 7:30 PM' },
  { id: 'game-004', level: 'pro', teamA: { name: 'B.M.T. Titans', score: 0, logo: '', record: '12-2', color: '#f97316' }, teamB: { name: 'Northside Kings', score: 0, logo: '', record: '11-3', color: '#10b981' }, status: 'upcoming', venue: 'Pan Am Centre, Scarborough', time: 'Tomorrow 2:00 PM' },
  { id: 'game-005', level: 'pro', teamA: { name: 'Scarborough Elite', score: 72, logo: '', record: '8-6', color: '#64748b' }, teamB: { name: 'Rexdale Runs', score: 65, logo: '', record: '7-7', color: '#ef4444' }, status: 'final', venue: 'Malvern Community Centre', time: 'Final', mvp: { name: 'DunkCity', stats: '22 PTS \u00b7 9 REB \u00b7 4 BLK', avatar: 'DC' }, impactScore: 85 },
  { id: 'game-010', level: 'collegiate', teamA: { name: 'UofT Varsity Blues', score: 81, logo: '', record: '14-2', color: '#1d4ed8' }, teamB: { name: 'TMU Bold', score: 74, logo: '', record: '11-5', color: '#7c3aed' }, status: 'live', venue: 'Goldring Centre, UofT', time: 'Q4 2:41', mvp: { name: 'Jaylen Carter', stats: '22 PTS \u00b7 6 AST', avatar: 'JC' }, impactScore: 78 },
  { id: 'game-011', level: 'collegiate', teamA: { name: 'York Lions', score: 0, logo: '', record: '9-7', color: '#dc2626' }, teamB: { name: 'Humber Hawks', score: 0, logo: '', record: '12-4', color: '#0ea5e9' }, status: 'upcoming', venue: 'Tait McKenzie Centre', time: 'Today 8:00 PM' },
  { id: 'game-012', level: 'collegiate', teamA: { name: 'Seneca Sting', score: 68, logo: '', record: '8-8', color: '#eab308' }, teamB: { name: 'George Brown Huskies', score: 59, logo: '', record: '6-10', color: '#059669' }, status: 'final', venue: 'Seneca @ York', time: 'Final', mvp: { name: 'Devon Ellis', stats: '19 PTS \u00b7 8 REB', avatar: 'DE' }, impactScore: 72 },
  { id: 'game-020', level: 'highschool', teamA: { name: 'Oakwood Barons', score: 62, logo: '', record: '16-1', color: '#8b5cf6' }, teamB: { name: 'Eastern Commerce Saints', score: 58, logo: '', record: '13-4', color: '#f59e0b' }, status: 'live', venue: 'Oakwood CI Gym', time: 'Q3 6:10', mvp: { name: 'Keon James', stats: '16 PTS \u00b7 5 STL', avatar: 'KJ' }, impactScore: 64 },
  { id: 'game-021', level: 'highschool', teamA: { name: 'Sir Wilfrid Laurier', score: 0, logo: '', record: '10-7', color: '#16a34a' }, teamB: { name: 'Westview Wildcats', score: 0, logo: '', record: '14-3', color: '#0891b2' }, status: 'upcoming', venue: 'Westview Secondary', time: 'Tomorrow 4:00 PM' },
  { id: 'game-022', level: 'highschool', teamA: { name: 'Birchmount Park CI', score: 55, logo: '', record: '9-8', color: '#e11d48' }, teamB: { name: 'Cedarbrae CI', score: 48, logo: '', record: '7-10', color: '#475569' }, status: 'final', venue: 'Birchmount Park Gym', time: 'Final', mvp: { name: 'Ayo Williams', stats: '14 PTS \u00b7 11 REB', avatar: 'AW' }, impactScore: 58 },
  { id: 'game-030', level: 'elementary', teamA: { name: 'Willow Park Jr.', score: 24, logo: '', record: '8-0', color: '#f97316' }, teamB: { name: 'Glamorgan Jr.', score: 18, logo: '', record: '6-2', color: '#6366f1' }, status: 'live', venue: 'Willow Park PS Gym', time: 'H2 3:45', impactScore: 34 },
  { id: 'game-031', level: 'elementary', teamA: { name: 'Poplar Road PS', score: 0, logo: '', record: '5-3', color: '#84cc16' }, teamB: { name: 'Cedarbrook PS', score: 0, logo: '', record: '7-1', color: '#ec4899' }, status: 'upcoming', venue: 'Cedarbrook PS', time: 'Wed 3:30 PM' },
  { id: 'game-032', level: 'elementary', teamA: { name: 'Corvette Jr.', score: 22, logo: '', record: '4-4', color: '#0ea5e9' }, teamB: { name: 'Highcastle PS', score: 20, logo: '', record: '3-5', color: '#a855f7' }, status: 'final', venue: 'Corvette Jr. PS', time: 'Final', impactScore: 28 },
];

export const TRENDING_TAGS: string[] = [
  '#ballinthe6', '#scarborough', '#toronto', '#6ixhoops',
  '#courtculture', '#gameday', '#mvp', '#impactscore',
];
