import type { Child, ParentEvent, CoachNote, GroupChat } from '@/types/parent';

export const PARENT_CHILDREN: Child[] = [
  {
    id: 'child-001',
    name: 'Tyrese M.',
    age: 13,
    avatar: 'TM',
    programs: [
      {
        programId: 'prog-001',
        programName: 'U14 Competitive Basketball',
        teamName: 'Scarborough Elite U14',
        sport: 'Basketball',
        nextEvent: {
          id: 'evt-001',
          date: '2026-03-21',
          time: '6:00 PM',
          type: 'practice',
          title: 'Team Practice',
          venue: 'Pan Am Centre, Scarborough',
          childId: 'child-001',
          childName: 'Tyrese M.',
        },
        paymentStatus: 'current',
        amountPaid: 1200,
        amountDue: 0,
      },
    ],
  },
  {
    id: 'child-002',
    name: 'Ava M.',
    age: 10,
    avatar: 'AM',
    programs: [
      {
        programId: 'prog-002',
        programName: 'Summer Basketball Camp',
        teamName: 'Ball in the 6 Summer Camp',
        sport: 'Basketball',
        nextEvent: {
          id: 'evt-005',
          date: '2026-03-23',
          time: '9:00 AM',
          type: 'clinic',
          title: 'Skills Clinic',
          venue: 'Downsview Park Gym',
          childId: 'child-002',
          childName: 'Ava M.',
        },
        paymentStatus: 'upcoming',
        amountPaid: 200,
        amountDue: 350,
      },
    ],
  },
];

export const PARENT_EVENTS: ParentEvent[] = [
  {
    id: 'evt-001',
    date: '2026-03-21',
    time: '6:00 PM',
    type: 'practice',
    title: 'Team Practice',
    venue: 'Pan Am Centre, Scarborough',
    childId: 'child-001',
    childName: 'Tyrese M.',
  },
  {
    id: 'evt-002',
    date: '2026-03-22',
    time: '2:00 PM',
    type: 'game',
    title: 'vs B.M.T. Titans',
    venue: 'Pan Am Centre, Scarborough',
    childId: 'child-001',
    childName: 'Tyrese M.',
  },
  {
    id: 'evt-003',
    date: '2026-03-23',
    time: '9:00 AM',
    type: 'clinic',
    title: 'Skills Clinic',
    venue: 'Downsview Park Gym',
    childId: 'child-002',
    childName: 'Ava M.',
  },
  {
    id: 'evt-004',
    date: '2026-03-24',
    time: '5:30 PM',
    type: 'practice',
    title: 'Shooting Drills',
    venue: "L'Amoreaux Sports Complex",
    childId: 'child-001',
    childName: 'Tyrese M.',
  },
  {
    id: 'evt-005',
    date: '2026-03-25',
    time: '7:00 PM',
    type: 'meeting',
    title: 'Parent-Coach Meeting',
    venue: 'Pan Am Centre, Room 204',
    childId: 'child-001',
    childName: 'Tyrese M.',
  },
  {
    id: 'evt-006',
    date: '2026-03-25',
    time: '4:00 PM',
    type: 'practice',
    title: 'Ball Handling Camp',
    venue: 'Downsview Park Gym',
    childId: 'child-002',
    childName: 'Ava M.',
  },
  {
    id: 'evt-007',
    date: '2026-03-26',
    time: '6:30 PM',
    type: 'game',
    title: 'vs Northside Kings',
    venue: 'Mattamy Athletic Centre',
    childId: 'child-001',
    childName: 'Tyrese M.',
  },
  {
    id: 'evt-008',
    date: '2026-03-27',
    time: '10:00 AM',
    type: 'clinic',
    title: 'Defense Fundamentals',
    venue: 'Downsview Park Gym',
    childId: 'child-002',
    childName: 'Ava M.',
  },
];

export const COACH_NOTES: CoachNote[] = [
  {
    id: 'note-001',
    date: '2026-03-20',
    coachName: 'Coach Williams',
    childName: 'Tyrese M.',
    content: 'Tyrese showed incredible court vision today. His no-look pass in the scrimmage was elite-level. He is reading defenses better every week.',
    type: 'praise',
  },
  {
    id: 'note-002',
    date: '2026-03-19',
    coachName: 'Coach Williams',
    childName: 'Tyrese M.',
    content: 'Need to work on left-hand finishing around the rim. Right now Tyrese is too predictable going right. We will focus on this in drills next week.',
    type: 'feedback',
  },
  {
    id: 'note-003',
    date: '2026-03-18',
    coachName: 'Coach Daniels',
    childName: 'Ava M.',
    content: 'Ava has been consistently improving her dribbling. She completed the full crossover drill set for the first time today. Great progress.',
    type: 'progress',
  },
  {
    id: 'note-004',
    date: '2026-03-17',
    coachName: 'Coach Williams',
    childName: 'Tyrese M.',
    content: 'Tyrese seemed frustrated during the last quarter of the scrimmage after a few turnovers. We talked about composure and staying locked in. Worth reinforcing at home.',
    type: 'concern',
  },
  {
    id: 'note-005',
    date: '2026-03-16',
    coachName: 'Coach Daniels',
    childName: 'Ava M.',
    content: 'Ava is the hardest worker in camp. She stays after every session to get extra shots up. That work ethic is contagious for the other kids.',
    type: 'praise',
  },
  {
    id: 'note-006',
    date: '2026-03-15',
    coachName: 'Coach Williams',
    childName: 'Tyrese M.',
    content: 'Tyrese is now leading the team in assists per game (5.2). His playmaking has taken a real leap since the start of the season.',
    type: 'progress',
  },
];

export const PARENT_GROUP_CHATS: GroupChat[] = [
  {
    id: 'gc-001',
    name: 'U14 Parents',
    memberCount: 24,
    programId: 'prog-001',
    lastMessage: 'Reminder: Saturday game moved to 2 PM',
    lastMessageAt: '10m ago',
    unread: 3,
  },
  {
    id: 'gc-002',
    name: 'Summer Camp Parents',
    memberCount: 18,
    programId: 'prog-002',
    lastMessage: 'Can someone bring extra water bottles Friday?',
    lastMessageAt: '1h ago',
    unread: 1,
  },
  {
    id: 'gc-003',
    name: 'Carpool Group',
    memberCount: 6,
    programId: 'prog-001',
    lastMessage: 'I can drive Thursday. Who needs a ride?',
    lastMessageAt: '3h ago',
    unread: 0,
  },
];
