import type { PlayerDetail, GameLog, PlayerHighlight } from '@/types/player';

/* ------------------------------------------------------------------ */
/*  Player Detail Profiles                                             */
/* ------------------------------------------------------------------ */

export const PLAYER_DETAILS: PlayerDetail[] = [
  {
    id: 'player-001',
    name: 'McKeyra',
    position: 'PG',
    number: 6,
    height: "6'2\"",
    weight: 185,
    age: 25,
    team: 'B.M.T. Titans',
    school: 'University of Toronto',
    stats: {
      gamesPlayed: 28,
      ppg: 24.8,
      rpg: 5.2,
      apg: 8.4,
      spg: 2.1,
      bpg: 0.4,
      fgPct: 48.6,
      threePct: 39.2,
      ftPct: 87.5,
      mpg: 34.6,
      topg: 2.8,
    },
    bio: 'Born and raised in Scarborough, McKeyra is the heartbeat of Toronto basketball. A floor general with an elite handle and court vision that makes everyone around him better. Founded Ball in the 6 to give Toronto hoopers a platform to showcase their game. Known for his signature crossover and clutch gene — when it matters most, he delivers. Three-time Toronto Pro League MVP and the undisputed king of the 6ix streetball scene.',
    accolades: [
      '3x Toronto Pro League MVP',
      'All-Toronto First Team (4 seasons)',
      'Pan Am Centre Scoring Record (52 PTS)',
      'Toronto Pro League Assists Leader (2 seasons)',
      'Ball in the 6 Founder',
      'OUA All-Star (UofT)',
    ],
    socialLinks: {
      instagram: '@mr_ballinthe6',
      twitter: '@mr_ballinthe6',
      tiktok: '@ballinthe6',
    },
  },
  {
    id: 'player-002',
    name: 'Caleb Smith',
    position: 'SG',
    number: 1,
    height: "6'4\"",
    weight: 195,
    age: 23,
    team: 'B.M.T. Titans',
    school: 'Toronto Metropolitan University',
    stats: {
      gamesPlayed: 26,
      ppg: 22.4,
      rpg: 4.8,
      apg: 3.6,
      spg: 1.5,
      bpg: 0.3,
      fgPct: 46.2,
      threePct: 41.8,
      ftPct: 85.2,
      mpg: 32.8,
      topg: 2.1,
    },
    bio: 'Caleb Smith is a scoring machine who can light it up from anywhere on the court. A product of the Scarborough basketball pipeline, he developed his game at Pan Am Centre before starring at TMU. His combination of size, shooting touch, and relentless motor makes him one of the most feared scorers in the Toronto Pro League. When Caleb gets hot, there is no stopping him — just ask the defenders who have tried.',
    accolades: [
      'Toronto Pro League Scoring Champion',
      'All-Toronto First Team (2 seasons)',
      'TMU Bold All-Conference',
      'Pan Am Classic MVP (2024)',
      '40+ Point Games: 4 this season',
    ],
    socialLinks: {
      instagram: '@caleb_buckets',
      twitter: '@caleb_buckets',
    },
  },
  {
    id: 'player-003',
    name: 'Marcus Thompson',
    position: 'SF',
    number: 13,
    height: "6'7\"",
    weight: 215,
    age: 24,
    team: 'Northside Kings',
    school: 'York University',
    stats: {
      gamesPlayed: 27,
      ppg: 20.6,
      rpg: 7.4,
      apg: 5.2,
      spg: 1.8,
      bpg: 1.1,
      fgPct: 50.4,
      threePct: 36.8,
      ftPct: 79.6,
      mpg: 35.2,
      topg: 2.4,
    },
    bio: 'Marcus Thompson is the definition of a two-way player. Standing 6\'7" with the handle of a guard and the athleticism of a wing, he is a matchup nightmare for anyone in the Toronto Pro League. Raised in North York, Marcus spent his summers dominating at Downsview Park before becoming a York Lions star. His versatility — scoring, rebounding, playmaking, and defending — makes him the most complete player in the league. The triple-double machine of the 6ix.',
    accolades: [
      'Toronto Pro League Defensive Player of the Year',
      'All-Toronto First Team (3 seasons)',
      'Triple-Double Record: 7 this season',
      'York Lions All-Canadian',
      'Downsview Classic Champion (3x)',
      'OUA Defensive Player of the Year',
    ],
    socialLinks: {
      instagram: '@marcust_6ix',
      twitter: '@marcust_6ix',
      tiktok: '@marcust_6ix',
    },
  },
  {
    id: 'player-004',
    name: 'DunkCity',
    position: 'PF',
    number: 44,
    height: "6'8\"",
    weight: 230,
    age: 22,
    team: 'Scarborough Elite',
    school: 'Seneca College',
    stats: {
      gamesPlayed: 24,
      ppg: 18.2,
      rpg: 9.6,
      apg: 2.1,
      spg: 0.9,
      bpg: 2.4,
      fgPct: 56.8,
      threePct: 28.4,
      ftPct: 68.2,
      mpg: 30.4,
      topg: 1.8,
    },
    bio: 'DunkCity is exactly what the name suggests — a poster machine who plays above the rim and punishes anyone brave enough to contest at the basket. Growing up in Scarborough, he earned his reputation at Cherry Beach open runs where he would posterize anyone in his path. At 6\'8" with a 40-inch vertical, he is the most explosive athlete in the Toronto Pro League. His highlight reel reads like a violence warning — enter the paint at your own risk.',
    accolades: [
      'Toronto Pro League Dunk Contest Champion (2x)',
      'All-Toronto Second Team',
      'League Leader: Blocks (2.4 BPG)',
      'Cherry Beach King of the Court',
      'Seneca Sting Rebounding Record',
      '30+ Dunk Highlights this season',
    ],
    socialLinks: {
      instagram: '@dunkcity_to',
      tiktok: '@dunkcity_to',
    },
  },
];

/* ------------------------------------------------------------------ */
/*  Game Logs — Last 10 games per player                               */
/* ------------------------------------------------------------------ */

export const PLAYER_GAME_LOGS: Record<string, GameLog[]> = {
  'player-001': [
    { date: 'Mar 18', opponent: 'Scarborough Elite', pts: 32, reb: 6, ast: 11, min: 38, result: 'W' },
    { date: 'Mar 15', opponent: 'East York Wolves', pts: 28, reb: 4, ast: 9, min: 36, result: 'W' },
    { date: 'Mar 12', opponent: 'Northside Kings', pts: 22, reb: 5, ast: 12, min: 35, result: 'L' },
    { date: 'Mar 9', opponent: 'Rexdale Runs', pts: 26, reb: 7, ast: 8, min: 34, result: 'W' },
    { date: 'Mar 6', opponent: 'SJPII Panthers', pts: 30, reb: 3, ast: 7, min: 37, result: 'W' },
    { date: 'Mar 3', opponent: 'Scarborough Elite', pts: 18, reb: 6, ast: 10, min: 32, result: 'W' },
    { date: 'Feb 28', opponent: 'Northside Kings', pts: 24, reb: 5, ast: 6, min: 33, result: 'W' },
    { date: 'Feb 25', opponent: 'East York Wolves', pts: 21, reb: 4, ast: 9, min: 31, result: 'W' },
    { date: 'Feb 22', opponent: 'Rexdale Runs', pts: 35, reb: 8, ast: 7, min: 40, result: 'W' },
    { date: 'Feb 19', opponent: 'SJPII Panthers', pts: 20, reb: 4, ast: 5, min: 30, result: 'L' },
  ],
  'player-002': [
    { date: 'Mar 18', opponent: 'Scarborough Elite', pts: 28, reb: 4, ast: 2, min: 36, result: 'W' },
    { date: 'Mar 15', opponent: 'East York Wolves', pts: 34, reb: 5, ast: 4, min: 38, result: 'W' },
    { date: 'Mar 12', opponent: 'Northside Kings', pts: 18, reb: 3, ast: 3, min: 32, result: 'L' },
    { date: 'Mar 9', opponent: 'Rexdale Runs', pts: 24, reb: 6, ast: 5, min: 34, result: 'W' },
    { date: 'Mar 6', opponent: 'SJPII Panthers', pts: 42, reb: 7, ast: 2, min: 40, result: 'W' },
    { date: 'Mar 3', opponent: 'Scarborough Elite', pts: 16, reb: 4, ast: 4, min: 30, result: 'W' },
    { date: 'Feb 28', opponent: 'Northside Kings', pts: 22, reb: 3, ast: 3, min: 33, result: 'W' },
    { date: 'Feb 25', opponent: 'East York Wolves', pts: 20, reb: 5, ast: 2, min: 31, result: 'W' },
    { date: 'Feb 22', opponent: 'Rexdale Runs', pts: 26, reb: 4, ast: 6, min: 35, result: 'W' },
    { date: 'Feb 19', opponent: 'SJPII Panthers', pts: 14, reb: 6, ast: 3, min: 28, result: 'L' },
  ],
  'player-003': [
    { date: 'Mar 18', opponent: 'Rexdale Runs', pts: 34, reb: 8, ast: 7, min: 38, result: 'W' },
    { date: 'Mar 15', opponent: 'B.M.T. Titans', pts: 26, reb: 9, ast: 5, min: 36, result: 'W' },
    { date: 'Mar 12', opponent: 'B.M.T. Titans', pts: 22, reb: 6, ast: 8, min: 37, result: 'W' },
    { date: 'Mar 9', opponent: 'East York Wolves', pts: 18, reb: 10, ast: 4, min: 34, result: 'W' },
    { date: 'Mar 6', opponent: 'Scarborough Elite', pts: 20, reb: 7, ast: 6, min: 35, result: 'L' },
    { date: 'Mar 3', opponent: 'SJPII Panthers', pts: 24, reb: 8, ast: 5, min: 36, result: 'W' },
    { date: 'Feb 28', opponent: 'Rexdale Runs', pts: 16, reb: 11, ast: 7, min: 33, result: 'W' },
    { date: 'Feb 25', opponent: 'Scarborough Elite', pts: 28, reb: 6, ast: 4, min: 37, result: 'W' },
    { date: 'Feb 22', opponent: 'East York Wolves', pts: 14, reb: 7, ast: 9, min: 32, result: 'L' },
    { date: 'Feb 19', opponent: 'B.M.T. Titans', pts: 30, reb: 5, ast: 3, min: 38, result: 'W' },
  ],
  'player-004': [
    { date: 'Mar 18', opponent: 'Rexdale Runs', pts: 22, reb: 12, ast: 2, min: 34, result: 'W' },
    { date: 'Mar 15', opponent: 'B.M.T. Titans', pts: 16, reb: 9, ast: 1, min: 30, result: 'L' },
    { date: 'Mar 12', opponent: 'Northside Kings', pts: 20, reb: 14, ast: 3, min: 32, result: 'L' },
    { date: 'Mar 9', opponent: 'East York Wolves', pts: 24, reb: 8, ast: 2, min: 33, result: 'W' },
    { date: 'Mar 6', opponent: 'SJPII Panthers', pts: 18, reb: 11, ast: 1, min: 31, result: 'W' },
    { date: 'Mar 3', opponent: 'Northside Kings', pts: 14, reb: 10, ast: 3, min: 28, result: 'L' },
    { date: 'Feb 28', opponent: 'Rexdale Runs', pts: 26, reb: 13, ast: 2, min: 35, result: 'W' },
    { date: 'Feb 25', opponent: 'B.M.T. Titans', pts: 12, reb: 8, ast: 1, min: 27, result: 'L' },
    { date: 'Feb 22', opponent: 'East York Wolves', pts: 20, reb: 10, ast: 4, min: 32, result: 'W' },
    { date: 'Feb 19', opponent: 'SJPII Panthers', pts: 16, reb: 9, ast: 2, min: 29, result: 'W' },
  ],
};

/* ------------------------------------------------------------------ */
/*  Player Highlights                                                   */
/* ------------------------------------------------------------------ */

export const PLAYER_HIGHLIGHTS: Record<string, PlayerHighlight[]> = {
  'player-001': [
    { id: 'hl-001', title: 'Ankle Breaker at Pan Am', description: 'Nasty crossover that sent the defender sliding, followed by a step-back three from the wing. Pan Am Centre erupted.', date: 'Mar 18', type: 'crossover' },
    { id: 'hl-002', title: 'No-Look Dime to Smith', description: 'Full-court press break into a behind-the-back no-look pass to Caleb Smith cutting baseline for the slam.', date: 'Mar 15', type: 'assist' },
    { id: 'hl-003', title: 'Buzzer-Beater vs Rexdale', description: 'Down two with 2.4 seconds left, McKeyra pulled up from 28 feet and drained the game-winner. Ice in his veins.', date: 'Feb 22', type: 'game-winner' },
    { id: 'hl-004', title: 'Triple-Threat Explosion', description: 'Triple jab from the left elbow, blew past two defenders for a euro-step finish at the rim. And the foul.', date: 'Mar 9', type: 'crossover' },
    { id: 'hl-005', title: 'Logo Three vs Panthers', description: 'Caught the ball at halfcourt, took two dribbles, and launched from the logo. Nothing but net. 30-piece complete.', date: 'Mar 6', type: 'three' },
  ],
  'player-002': [
    { id: 'hl-006', title: '42-Point Eruption', description: 'Caleb went nuclear against SJPII — 42 points on 15-of-22 shooting including 8 threes. A scoring clinic from start to finish.', date: 'Mar 6', type: 'three' },
    { id: 'hl-007', title: 'Poster Dunk on Edwards', description: 'Caught the ball on the wing, drove baseline, and elevated over Kyle Edwards for a one-handed slam. Disrespectful.', date: 'Mar 15', type: 'dunk' },
    { id: 'hl-008', title: 'Step-Back Dagger', description: 'Game tied with 8 seconds left, Caleb iso\'d his man, hit him with a double crossover into a step-back three. Game. Over.', date: 'Mar 9', type: 'game-winner' },
    { id: 'hl-009', title: 'Corner Three Barrage', description: 'Hit four consecutive corner threes in the third quarter to blow the game open. Defenders could not get close enough.', date: 'Feb 28', type: 'three' },
    { id: 'hl-010', title: 'Transition Slam', description: 'Stole the ball at halfcourt, took two dribbles, and threw down a windmill dunk in transition. The bench lost its mind.', date: 'Feb 22', type: 'dunk' },
  ],
  'player-003': [
    { id: 'hl-011', title: 'Triple-Double Machine', description: '34 points, 8 rebounds, 7 assists against Rexdale. Marcus controlled every aspect of the game from tip to final buzzer.', date: 'Mar 18', type: 'assist' },
    { id: 'hl-012', title: 'Chase-Down Block', description: 'Sprinted back from halfcourt to pin a layup attempt off the backboard. Shades of LeBron. The crowd went silent then erupted.', date: 'Mar 12', type: 'block' },
    { id: 'hl-013', title: 'Coast-to-Coast Slam', description: 'Grabbed the defensive rebound, took it coast-to-coast through three defenders, and finished with a two-handed poster dunk.', date: 'Feb 25', type: 'dunk' },
    { id: 'hl-014', title: 'Alley-Oop Connection', description: 'Threw himself a lob off the backboard, caught it mid-air, and finished with his off-hand. Downsview Park has never been louder.', date: 'Mar 3', type: 'dunk' },
    { id: 'hl-015', title: 'Game-Winner at the Horn', description: 'Caught the inbound, spun past his defender, and hit a fadeaway from 15 feet as the buzzer sounded. Northside wins.', date: 'Feb 19', type: 'game-winner' },
  ],
  'player-004': [
    { id: 'hl-016', title: 'Poster of the Year', description: 'DunkCity caught a body at Cherry Beach. Drove baseline, elevated over two defenders, and threw down a vicious one-handed slam. The video went viral.', date: 'Mar 18', type: 'dunk' },
    { id: 'hl-017', title: 'Quadruple Block Party', description: 'Four blocks in a single quarter. DunkCity was a brick wall in the paint, swatting everything that came near the rim.', date: 'Mar 6', type: 'block' },
    { id: 'hl-018', title: 'Put-Back Windmill', description: 'Offensive rebound on a missed three — DunkCity grabbed it at the peak and finished with a one-handed windmill put-back. Inhuman.', date: 'Feb 28', type: 'dunk' },
    { id: 'hl-019', title: 'Alley-Oop Hammer', description: 'Caught the lob from halfcourt on a fast break and threw down a tomahawk dunk so hard the rim was shaking for 10 seconds.', date: 'Feb 22', type: 'dunk' },
    { id: 'hl-020', title: '20-20 Game', description: '26 points and 13 rebounds against Rexdale. DunkCity dominated the paint on both ends, finishing with 4 blocks and 2 steals.', date: 'Feb 28', type: 'block' },
  ],
};
