import {
  type FanProfile,
  type PlayerProfile,
  type TeamProfile,
  type CoachProfile,
  type OrganizationProfile,
  type BusinessProfile,
  type AnyProfile,
  PROFILE_TOKEN_PRESETS,
} from '@/types/profiles';

export const FAN_PROFILE: FanProfile = {
  id: 'fan-001',
  type: 'fan',
  displayName: 'Tyrese Montague',
  handle: '@tyrese_6ix',
  avatar: '',
  bio: 'Die-hard Raptors fan since day one. Section 108 regular. If you bleed red, we rock. Toronto basketball is a lifestyle.',
  location: 'Scarborough, ON',
  joinedDate: '2024-01-15',
  verified: true,
  followers: 4820,
  following: 1240,
  tokens: PROFILE_TOKEN_PRESETS.fan,
  links: [
    { platform: 'twitter', url: 'https://twitter.com/tyrese_6ix', label: '@tyrese_6ix' },
    { platform: 'instagram', url: 'https://instagram.com/tyrese_6ix', label: '@tyrese_6ix' },
  ],
  stats: {
    gamesAttended: 147,
    impactScore: 8920,
    assistsGiven: 634,
    favoriteTeam: 'Toronto Raptors',
    streak: 12,
  },
};

export const PLAYER_PROFILE: PlayerProfile = {
  id: 'player-001',
  type: 'player',
  displayName: 'Caleb Smith',
  handle: '@caleb_buckets',
  avatar: '',
  bio: 'Point guard out of Scarborough. Grade 12 at Birchmount Park CI. D1 committed. Let the game speak.',
  location: 'Scarborough, ON',
  joinedDate: '2024-03-08',
  verified: true,
  followers: 11200,
  following: 380,
  tokens: PROFILE_TOKEN_PRESETS.player,
  links: [
    { platform: 'twitter', url: 'https://twitter.com/caleb_buckets', label: '@caleb_buckets' },
    { platform: 'hudl', url: 'https://hudl.com/caleb-smith', label: 'Hudl Film' },
  ],
  stats: {
    ppg: 24.6,
    apg: 7.2,
    rpg: 4.8,
    impactScore: 11200,
    gamesPlayed: 42,
    rank: 2,
    streak: 9,
  },
  position: 'Point Guard',
  jerseyNumber: 3,
  team: 'B.M.T. Titans',
  height: '6\'1"',
  experience: 'Grade 12 / Senior',
};

export const TEAM_PROFILE: TeamProfile = {
  id: 'team-001',
  type: 'team',
  displayName: 'B.M.T. Titans',
  handle: '@bmt_titans',
  avatar: '',
  bio: 'Scarborough AAU program. Developing the next generation of Toronto basketball talent since 2018. Multiple provincial championships.',
  location: 'Scarborough, ON',
  joinedDate: '2024-02-01',
  verified: true,
  followers: 8400,
  following: 210,
  tokens: PROFILE_TOKEN_PRESETS.team,
  links: [
    { platform: 'website', url: 'https://bmttitans.ca', label: 'bmttitans.ca' },
    { platform: 'instagram', url: 'https://instagram.com/bmt_titans', label: '@bmt_titans' },
  ],
  stats: {
    wins: 12,
    losses: 2,
    impactScore: 9400,
    rosterSize: 14,
    championships: 3,
  },
  league: 'Toronto AAU League',
  division: 'U18 Elite',
  homeCourt: 'Pan Am Centre, Scarborough',
  roster: [
    { name: 'Caleb Smith', number: 3, position: 'PG', avatar: '' },
    { name: 'Jaylen Harris', number: 11, position: 'SG', avatar: '' },
    { name: 'Darius Cole', number: 24, position: 'SF', avatar: '' },
    { name: 'Andre Williams', number: 32, position: 'PF', avatar: '' },
    { name: 'Marcus Brown', number: 45, position: 'C', avatar: '' },
    { name: 'Keon James', number: 7, position: 'PG', avatar: '' },
    { name: 'Tyrell Davis', number: 14, position: 'SG', avatar: '' },
    { name: 'Nathan Chen', number: 20, position: 'SF', avatar: '' },
    { name: 'Isaiah Grant', number: 33, position: 'PF', avatar: '' },
    { name: 'Devon Ellis', number: 50, position: 'C', avatar: '' },
    { name: 'Malik Roberts', number: 5, position: 'PG', avatar: '' },
    { name: 'Chris Park', number: 15, position: 'SG', avatar: '' },
    { name: 'Amir Thompson', number: 22, position: 'SF', avatar: '' },
    { name: 'Jordan Lee', number: 41, position: 'PF', avatar: '' },
  ],
};

export const COACH_PROFILE: CoachProfile = {
  id: 'coach-001',
  type: 'coach',
  displayName: 'Coach Dwayne Mitchell',
  handle: '@coach_d_mitchell',
  avatar: '',
  bio: 'Head coach, B.M.T. Titans. NCCP certified. 15 years developing young talent in Scarborough. Defence wins championships.',
  location: 'Scarborough, ON',
  joinedDate: '2024-01-20',
  verified: true,
  followers: 3200,
  following: 520,
  tokens: PROFILE_TOKEN_PRESETS.coach,
  links: [
    { platform: 'linkedin', url: 'https://linkedin.com/in/dwaynemitchell', label: 'LinkedIn' },
  ],
  stats: {
    wins: 312,
    losses: 94,
    playersCoached: 184,
    programsRun: 6,
    yearsExperience: 15,
    rating: 4.9,
  },
  certifications: [
    'NCCP Competition — Development',
    'NCCP Learn to Train',
    'First Aid & CPR Level C',
    'Respect in Sport — Activity Leader',
    'FIBA Mini Basketball Certified',
  ],
  currentTeam: 'B.M.T. Titans',
  specialty: 'Point Guard Development & Defensive Systems',
};

export const ORG_PROFILE: OrganizationProfile = {
  id: 'org-001',
  type: 'organization',
  displayName: 'Toronto Metro Basketball League',
  handle: '@tmbl_official',
  avatar: '',
  bio: 'Official league organizing competitive basketball across the GTA. 64 teams, 8 divisions, 1 city. Registration open year-round.',
  location: 'Toronto, ON',
  joinedDate: '2024-01-01',
  verified: true,
  followers: 14600,
  following: 85,
  tokens: PROFILE_TOKEN_PRESETS.organization,
  links: [
    { platform: 'website', url: 'https://tmbl.ca', label: 'tmbl.ca' },
    { platform: 'email', url: 'mailto:info@tmbl.ca', label: 'info@tmbl.ca' },
  ],
  stats: {
    activePrograms: 12,
    totalPlayers: 2480,
    teamsManaged: 64,
    revenue: 0,
    eventsHosted: 156,
  },
  entityType: 'league',
  programs: [
    { name: 'Summer Pro-Am', type: 'League', participants: 640 },
    { name: 'Winter Classic', type: 'Tournament', participants: 480 },
    { name: 'Youth Development Camp', type: 'Camp', participants: 320 },
    { name: 'Fall Ball', type: 'League', participants: 560 },
    { name: 'March Madness TO', type: 'Tournament', participants: 384 },
  ],
};

export const BIZ_PROFILE: BusinessProfile = {
  id: 'biz-001',
  type: 'business',
  displayName: 'Court Culture Supply',
  handle: '@courtculture_to',
  avatar: '',
  bio: 'Toronto\'s home for basketball gear, custom jerseys, and court culture. Proudly sponsoring local teams since 2019. Pull up.',
  location: '2847 Eglinton Ave E, Scarborough, ON',
  joinedDate: '2024-02-15',
  verified: true,
  followers: 6300,
  following: 340,
  tokens: PROFILE_TOKEN_PRESETS.business,
  links: [
    { platform: 'website', url: 'https://courtculturesupply.ca', label: 'courtculturesupply.ca' },
    { platform: 'instagram', url: 'https://instagram.com/courtculture_to', label: '@courtculture_to' },
  ],
  stats: {
    sponsorships: 8,
    eventsSponsored: 24,
    communityReach: 45000,
    rating: 4.7,
  },
  category: 'Sports Retail & Custom Apparel',
  address: '2847 Eglinton Ave E, Scarborough, ON M1J 2E2',
  hours: 'Mon-Sat 10AM-8PM, Sun 11AM-6PM',
  offerings: [
    'Custom Team Jerseys',
    'Basketball Shoes',
    'Training Equipment',
    'Streetwear Collection',
    'Court Accessories',
    'Team Uniform Packages',
  ],
};

export const ALL_PROFILES: AnyProfile[] = [
  FAN_PROFILE,
  PLAYER_PROFILE,
  TEAM_PROFILE,
  COACH_PROFILE,
  ORG_PROFILE,
  BIZ_PROFILE,
];
