import type { SportConfig } from './types';

export const baseball: SportConfig = {
  id: 'baseball',
  name: 'Baseball',
  emoji: '\u26BE',
  color: '#DC2626',
  courtType: 'diamond',
  positions: [
    {
      code: 'P', name: 'Pitcher', archetype: 'The Ace', color: '#EF4444',
      goat: 'Nolan Ryan', goatCountry: 'USA',
      radarDimensions: [
        { key: 'velocity', label: 'Velocity', goatScore: 99 },
        { key: 'control', label: 'Control', goatScore: 88 },
        { key: 'movement', label: 'Pitch Movement', goatScore: 95 },
        { key: 'durability', label: 'Durability', goatScore: 99 },
        { key: 'pitch_variety', label: 'Pitch Variety', goatScore: 92 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 97 },
        { key: 'strikeouts', label: 'Strikeout Ability', goatScore: 99 },
        { key: 'composure', label: 'Composure', goatScore: 95 },
        { key: 'fielding', label: 'Fielding', goatScore: 80 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
      ],
    },
    {
      code: 'C', name: 'Catcher', archetype: 'The Field General', color: '#8B5CF6',
      goat: 'Johnny Bench', goatCountry: 'USA',
      radarDimensions: [
        { key: 'framing', label: 'Pitch Framing', goatScore: 96 },
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 98 },
        { key: 'game_calling', label: 'Game Calling', goatScore: 99 },
        { key: 'blocking', label: 'Blocking', goatScore: 95 },
        { key: 'hitting', label: 'Hitting', goatScore: 94 },
        { key: 'power', label: 'Power', goatScore: 96 },
        { key: 'durability', label: 'Durability', goatScore: 93 },
        { key: 'leadership', label: 'Leadership', goatScore: 98 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 99 },
        { key: 'pop_time', label: 'Pop Time', goatScore: 95 },
      ],
    },
    {
      code: '1B', name: 'First Baseman', archetype: 'The Power Bat', color: '#F59E0B',
      goat: 'Lou Gehrig', goatCountry: 'USA',
      radarDimensions: [
        { key: 'hitting', label: 'Hitting', goatScore: 99 },
        { key: 'power', label: 'Power', goatScore: 98 },
        { key: 'plate_discipline', label: 'Plate Discipline', goatScore: 95 },
        { key: 'fielding', label: 'Fielding', goatScore: 90 },
        { key: 'scoops', label: 'Scooping Throws', goatScore: 92 },
        { key: 'durability', label: 'Durability', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Hitting', goatScore: 97 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'run_production', label: 'Run Production', goatScore: 98 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 93 },
      ],
    },
    {
      code: '2B', name: 'Second Baseman', archetype: 'The Catalyst', color: '#3B82F6',
      goat: 'Rogers Hornsby', goatCountry: 'USA',
      radarDimensions: [
        { key: 'hitting', label: 'Hitting', goatScore: 99 },
        { key: 'fielding', label: 'Fielding', goatScore: 88 },
        { key: 'double_play', label: 'Double Play Turn', goatScore: 90 },
        { key: 'range', label: 'Range', goatScore: 85 },
        { key: 'speed', label: 'Speed', goatScore: 82 },
        { key: 'plate_discipline', label: 'Plate Discipline', goatScore: 93 },
        { key: 'bat_control', label: 'Bat Control', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 97 },
        { key: 'clutch', label: 'Clutch Hitting', goatScore: 94 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 92 },
      ],
    },
    {
      code: '3B', name: 'Third Baseman', archetype: 'The Hot Corner', color: '#10B981',
      goat: 'Mike Schmidt', goatCountry: 'USA',
      radarDimensions: [
        { key: 'power', label: 'Power', goatScore: 98 },
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 96 },
        { key: 'reflexes', label: 'Reflexes', goatScore: 95 },
        { key: 'fielding', label: 'Fielding', goatScore: 97 },
        { key: 'hitting', label: 'Hitting', goatScore: 93 },
        { key: 'range', label: 'Range', goatScore: 90 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 92 },
        { key: 'durability', label: 'Durability', goatScore: 90 },
        { key: 'consistency', label: 'Consistency', goatScore: 93 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 94 },
      ],
    },
    {
      code: 'SS', name: 'Shortstop', archetype: 'The Magician', color: '#EC4899',
      goat: 'Honus Wagner', goatCountry: 'USA',
      radarDimensions: [
        { key: 'fielding', label: 'Fielding', goatScore: 99 },
        { key: 'range', label: 'Range', goatScore: 98 },
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 95 },
        { key: 'hitting', label: 'Hitting', goatScore: 97 },
        { key: 'speed', label: 'Speed', goatScore: 95 },
        { key: 'double_play', label: 'Double Play Turn', goatScore: 96 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 96 },
        { key: 'consistency', label: 'Consistency', goatScore: 94 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 93 },
        { key: 'leadership', label: 'Leadership', goatScore: 92 },
      ],
    },
    {
      code: 'LF', name: 'Left Fielder', archetype: 'The Slugger', color: '#F97316',
      goat: 'Ted Williams', goatCountry: 'USA',
      radarDimensions: [
        { key: 'hitting', label: 'Hitting', goatScore: 99 },
        { key: 'plate_discipline', label: 'Plate Discipline', goatScore: 99 },
        { key: 'power', label: 'Power', goatScore: 97 },
        { key: 'bat_control', label: 'Bat Control', goatScore: 99 },
        { key: 'fielding', label: 'Fielding', goatScore: 82 },
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 88 },
        { key: 'clutch', label: 'Clutch Hitting', goatScore: 96 },
        { key: 'consistency', label: 'Consistency', goatScore: 98 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 97 },
        { key: 'durability', label: 'Durability', goatScore: 88 },
      ],
    },
    {
      code: 'CF', name: 'Center Fielder', archetype: 'The Five-Tool', color: '#06B6D4',
      goat: 'Willie Mays', goatCountry: 'USA',
      radarDimensions: [
        { key: 'hitting', label: 'Hitting', goatScore: 97 },
        { key: 'power', label: 'Power', goatScore: 96 },
        { key: 'speed', label: 'Speed', goatScore: 97 },
        { key: 'fielding', label: 'Fielding', goatScore: 99 },
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 98 },
        { key: 'range', label: 'Range', goatScore: 99 },
        { key: 'base_running', label: 'Base Running', goatScore: 95 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 97 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 94 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
      ],
    },
    {
      code: 'RF', name: 'Right Fielder', archetype: 'The Cannon', color: '#84CC16',
      goat: 'Babe Ruth', goatCountry: 'USA',
      radarDimensions: [
        { key: 'power', label: 'Power', goatScore: 99 },
        { key: 'hitting', label: 'Hitting', goatScore: 98 },
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 95 },
        { key: 'plate_discipline', label: 'Plate Discipline', goatScore: 96 },
        { key: 'fielding', label: 'Fielding', goatScore: 85 },
        { key: 'run_production', label: 'Run Production', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Hitting', goatScore: 97 },
        { key: 'durability', label: 'Durability', goatScore: 92 },
        { key: 'baseball_iq', label: 'Baseball IQ', goatScore: 93 },
        { key: 'consistency', label: 'Consistency', goatScore: 95 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'at_bats', label: 'AB', type: 'number' },
    { key: 'hits', label: 'H', type: 'number' },
    { key: 'runs', label: 'R', type: 'number' },
    { key: 'home_runs', label: 'HR', type: 'number' },
    { key: 'rbi', label: 'RBI', type: 'number' },
    { key: 'strikeouts', label: 'K', type: 'number' },
    { key: 'walks', label: 'BB', type: 'number' },
    { key: 'stolen_bases', label: 'SB', type: 'number' },
    { key: 'era', label: 'ERA', type: 'decimal' },
    { key: 'batting_avg', label: 'AVG', type: 'decimal' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '5-12', color: '#F59E0B',
      philosophy: 'Learn to love the game through tee-ball, coach-pitch, and fundamentals.',
      keyFocus: ['Throwing mechanics', 'Catching basics', 'Hitting off a tee', 'Base running'],
      restrictions: ['Pitch count limits (Baseball Canada)', 'No curveballs under 14', 'Equal playing time'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '13-18', color: '#10B981',
      philosophy: 'Develop position-specific skills and compete in high school and rep leagues.',
      keyFocus: ['Position specialization', 'Pitch development', 'Situational hitting', 'Strength training'],
      restrictions: ['Pitch count limits', 'Academic balance', 'Baseball Canada arm-care guidelines'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-23', color: '#3B82F6',
      philosophy: 'Compete at the collegiate level and develop professional-grade tools.',
      keyFocus: ['Advanced scouting', 'Pitch sequencing', 'Advanced hitting approach', 'Pro-style conditioning'],
      restrictions: ['NCAA/CCBA eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '18+', color: '#8B5CF6',
      philosophy: 'Perform at the highest level in MLB, MiLB, or international competition.',
      keyFocus: ['Elite adjustments', 'Recovery & longevity', 'Mental performance', 'Pitch design'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    P: [
      { name: 'The Flamethrower', description: 'Overpowers hitters with elite velocity', traits: ['Velocity', 'Power', 'Intimidation'] },
      { name: 'The Craftsman', description: 'Mixes pitches and locates with surgical precision', traits: ['Control', 'Deception', 'Sequencing'] },
      { name: 'The Workhorse', description: 'Eats innings and goes deep into games every start', traits: ['Durability', 'Efficiency', 'Toughness'] },
      { name: 'The Closer', description: 'Shuts the door in high-leverage situations', traits: ['Clutch', 'Composure', 'Dominance'] },
    ],
    C: [
      { name: 'The Field General', description: 'Calls a masterful game and controls the pitching staff', traits: ['Game calling', 'Leadership', 'IQ'] },
      { name: 'The Backstop', description: 'Elite defensive catcher who blocks and frames everything', traits: ['Blocking', 'Framing', 'Receiving'] },
      { name: 'The Offensive Catcher', description: 'Rare power bat behind the plate', traits: ['Hitting', 'Power', 'Run production'] },
      { name: 'The Gunner', description: 'Throws out runners with an elite arm', traits: ['Arm strength', 'Pop time', 'Accuracy'] },
    ],
    '1B': [
      { name: 'The Masher', description: 'Middle-of-the-order slugger who drives in runs', traits: ['Power', 'RBI production', 'Strength'] },
      { name: 'The Contact King', description: 'High-average hitter with gap-to-gap power', traits: ['Bat control', 'Consistency', 'Plate discipline'] },
      { name: 'The Gold Glover', description: 'Picks everything at first and saves errors', traits: ['Fielding', 'Scoops', 'Footwork'] },
      { name: 'The OBP Machine', description: 'Gets on base at an elite rate through walks and hits', traits: ['Plate discipline', 'Eye', 'Patience'] },
    ],
    '2B': [
      { name: 'The Catalyst', description: 'Sets the table and sparks the offense from the top', traits: ['Speed', 'Contact', 'Base running'] },
      { name: 'The Gamer', description: 'Gritty middle infielder who always makes the play', traits: ['Toughness', 'Instinct', 'Hustle'] },
      { name: 'The Pivot', description: 'Smooth double-play turn with reliable glove', traits: ['Double play', 'Hands', 'Footwork'] },
      { name: 'The Power 2B', description: 'Rare pop from the second base position', traits: ['Power', 'Hitting', 'Strength'] },
    ],
    '3B': [
      { name: 'The Hot Corner', description: 'Quick reactions and a cannon arm at third', traits: ['Reflexes', 'Arm strength', 'Toughness'] },
      { name: 'The Run Producer', description: 'Cleanup hitter who drives in runs consistently', traits: ['Power', 'RBI production', 'Clutch'] },
      { name: 'The Vacuum', description: 'Nothing gets past this defender at third', traits: ['Fielding', 'Range', 'Hands'] },
      { name: 'The Complete 3B', description: 'Elite on both sides of the ball at the hot corner', traits: ['Versatility', 'Consistency', 'IQ'] },
    ],
    SS: [
      { name: 'The Magician', description: 'Makes impossible plays look routine', traits: ['Range', 'Hands', 'Arm strength'] },
      { name: 'The Offensive SS', description: 'Rare bat combined with solid defense', traits: ['Hitting', 'Power', 'Speed'] },
      { name: 'The Captain', description: 'Natural leader who runs the infield', traits: ['Leadership', 'Communication', 'IQ'] },
      { name: 'The Spark Plug', description: 'Speed and energy at the top of the lineup', traits: ['Speed', 'Base running', 'Contact'] },
    ],
    LF: [
      { name: 'The Slugger', description: 'Pure power bat who changes games with one swing', traits: ['Power', 'Bat speed', 'Strength'] },
      { name: 'The Pure Hitter', description: 'Gets hits in every at-bat with elite bat control', traits: ['Contact', 'Bat control', 'Eye'] },
      { name: 'The Gapper', description: 'Drives balls into the gaps for extra-base hits', traits: ['Gap power', 'Speed', 'Bat path'] },
      { name: 'The Patient Hitter', description: 'Works counts and wears out pitchers', traits: ['Plate discipline', 'Patience', 'OBP'] },
    ],
    CF: [
      { name: 'The Five-Tool', description: 'Can do everything at an elite level', traits: ['Hitting', 'Power', 'Speed', 'Fielding', 'Arm'] },
      { name: 'The Speedster', description: 'Covers ground like no other and steals bases', traits: ['Speed', 'Range', 'Base running'] },
      { name: 'The Glove', description: 'Elite range and route running in center', traits: ['Fielding', 'Range', 'Route running'] },
      { name: 'The Leadoff', description: 'Table setter who gets on base and scores', traits: ['OBP', 'Speed', 'Contact'] },
    ],
    RF: [
      { name: 'The Cannon', description: 'Elite arm that prevents runners from taking extra bases', traits: ['Arm strength', 'Accuracy', 'Throwing'] },
      { name: 'The Slugger', description: 'Power bat who anchors the middle of the order', traits: ['Power', 'Hitting', 'RBI production'] },
      { name: 'The Complete OF', description: 'Strong defensive outfielder with a solid bat', traits: ['Fielding', 'Arm', 'Hitting'] },
      { name: 'The Clutch Bat', description: 'Delivers in the biggest moments of the game', traits: ['Clutch', 'Composure', 'Experience'] },
    ],
  },
  personaQuiz: [
    {
      question: 'Bases loaded, bottom of the ninth. What do you want to do?',
      options: [
        { text: 'Hit a grand slam to win it', archetypes: { P: 'The Flamethrower', C: 'The Offensive Catcher', '1B': 'The Masher', '2B': 'The Power 2B', '3B': 'The Run Producer', SS: 'The Offensive SS', LF: 'The Slugger', CF: 'The Five-Tool', RF: 'The Slugger' } },
        { text: 'Work a walk to tie the game', archetypes: { P: 'The Craftsman', C: 'The Field General', '1B': 'The OBP Machine', '2B': 'The Catalyst', '3B': 'The Complete 3B', SS: 'The Captain', LF: 'The Patient Hitter', CF: 'The Leadoff', RF: 'The Complete OF' } },
        { text: 'Drive a single into the gap', archetypes: { P: 'The Workhorse', C: 'The Backstop', '1B': 'The Contact King', '2B': 'The Gamer', '3B': 'The Vacuum', SS: 'The Magician', LF: 'The Pure Hitter', CF: 'The Glove', RF: 'The Clutch Bat' } },
        { text: 'Strike out the side if I\'m pitching', archetypes: { P: 'The Closer', C: 'The Gunner', '1B': 'The Gold Glover', '2B': 'The Pivot', '3B': 'The Hot Corner', SS: 'The Spark Plug', LF: 'The Gapper', CF: 'The Speedster', RF: 'The Cannon' } },
      ],
    },
    {
      question: 'What part of practice do you enjoy most?',
      options: [
        { text: 'Batting practice', archetypes: { P: 'The Flamethrower', C: 'The Offensive Catcher', '1B': 'The Masher', '2B': 'The Power 2B', '3B': 'The Run Producer', SS: 'The Offensive SS', LF: 'The Slugger', CF: 'The Five-Tool', RF: 'The Slugger' } },
        { text: 'Fielding drills', archetypes: { P: 'The Workhorse', C: 'The Backstop', '1B': 'The Gold Glover', '2B': 'The Pivot', '3B': 'The Vacuum', SS: 'The Magician', LF: 'The Gapper', CF: 'The Glove', RF: 'The Cannon' } },
        { text: 'Base running and speed work', archetypes: { P: 'The Closer', C: 'The Gunner', '1B': 'The Contact King', '2B': 'The Catalyst', '3B': 'The Hot Corner', SS: 'The Spark Plug', LF: 'The Pure Hitter', CF: 'The Speedster', RF: 'The Complete OF' } },
        { text: 'Situational game scenarios', archetypes: { P: 'The Craftsman', C: 'The Field General', '1B': 'The OBP Machine', '2B': 'The Gamer', '3B': 'The Complete 3B', SS: 'The Captain', LF: 'The Patient Hitter', CF: 'The Leadoff', RF: 'The Clutch Bat' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The most dangerous bat in the lineup', archetypes: { P: 'The Flamethrower', C: 'The Offensive Catcher', '1B': 'The Masher', '2B': 'The Power 2B', '3B': 'The Run Producer', SS: 'The Offensive SS', LF: 'The Slugger', CF: 'The Five-Tool', RF: 'The Slugger' } },
        { text: 'The smartest player on the field', archetypes: { P: 'The Craftsman', C: 'The Field General', '1B': 'The OBP Machine', '2B': 'The Gamer', '3B': 'The Complete 3B', SS: 'The Captain', LF: 'The Patient Hitter', CF: 'The Leadoff', RF: 'The Clutch Bat' } },
        { text: 'The best defender on the team', archetypes: { P: 'The Workhorse', C: 'The Backstop', '1B': 'The Gold Glover', '2B': 'The Pivot', '3B': 'The Vacuum', SS: 'The Magician', LF: 'The Gapper', CF: 'The Glove', RF: 'The Cannon' } },
        { text: 'The fastest player on the roster', archetypes: { P: 'The Closer', C: 'The Gunner', '1B': 'The Contact King', '2B': 'The Catalyst', '3B': 'The Hot Corner', SS: 'The Spark Plug', LF: 'The Pure Hitter', CF: 'The Speedster', RF: 'The Complete OF' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Home Runs', archetypes: { P: 'The Flamethrower', C: 'The Offensive Catcher', '1B': 'The Masher', '2B': 'The Power 2B', '3B': 'The Run Producer', SS: 'The Offensive SS', LF: 'The Slugger', CF: 'The Five-Tool', RF: 'The Slugger' } },
        { text: 'Batting Average', archetypes: { P: 'The Craftsman', C: 'The Field General', '1B': 'The Contact King', '2B': 'The Gamer', '3B': 'The Complete 3B', SS: 'The Captain', LF: 'The Pure Hitter', CF: 'The Leadoff', RF: 'The Clutch Bat' } },
        { text: 'Stolen Bases', archetypes: { P: 'The Closer', C: 'The Gunner', '1B': 'The OBP Machine', '2B': 'The Catalyst', '3B': 'The Hot Corner', SS: 'The Spark Plug', LF: 'The Gapper', CF: 'The Speedster', RF: 'The Complete OF' } },
        { text: 'ERA / Fielding Percentage', archetypes: { P: 'The Workhorse', C: 'The Backstop', '1B': 'The Gold Glover', '2B': 'The Pivot', '3B': 'The Vacuum', SS: 'The Magician', LF: 'The Patient Hitter', CF: 'The Glove', RF: 'The Cannon' } },
      ],
    },
  ],
  drills: [
    { name: 'Long Toss Program', position: 'P', difficulty: 3, description: 'Progressive throwing at increasing distances to build arm strength', equipment: ['Baseball', 'Glove'] },
    { name: 'Tee Work Sequence', position: 'ALL', difficulty: 2, description: 'Hit off a tee at 5 different heights and locations', equipment: ['Bat', 'Tee', 'Baseballs'] },
    { name: 'Blocking Drill', position: 'C', difficulty: 3, description: 'Block balls in the dirt from all angles', equipment: ['Catcher gear', 'Baseballs'] },
    { name: 'Ground Ball Fungo', position: 'SS', difficulty: 3, description: 'Field grounders and make throws from multiple angles', equipment: ['Glove', 'Baseballs', 'Fungo bat'] },
    { name: 'Fly Ball Routes', position: 'CF', difficulty: 3, description: 'Read fly balls off the bat and run proper routes', equipment: ['Glove', 'Baseballs', 'Fungo bat'] },
    { name: 'Bullpen Session', position: 'P', difficulty: 4, description: 'Throw all pitches to targets in a simulated game', equipment: ['Baseballs', 'Mound', 'Catcher'] },
  ],
  benchmarks: [
    { name: '60-Yard Dash', unit: 'seconds', youth: 9.5, school: 7.5, university: 6.9, professional: 6.4 },
    { name: 'Throwing Velocity (IF)', unit: 'mph', youth: 45, school: 70, university: 82, professional: 90 },
    { name: 'Exit Velocity', unit: 'mph', youth: 55, school: 78, university: 90, professional: 100 },
    { name: 'Pitching Velocity', unit: 'mph', youth: 50, school: 75, university: 88, professional: 95 },
  ],
};
