import type { SportConfig } from './types';

export const basketball: SportConfig = {
  id: 'basketball',
  name: 'Basketball',
  emoji: '\u{1F3C0}',
  color: '#FF6B35',
  courtType: 'court',
  positions: [
    {
      code: 'PG', name: 'Point Guard', archetype: 'The Floor General', color: '#3B82F6',
      goat: 'Magic Johnson', goatCountry: 'USA',
      radarDimensions: [
        { key: 'ball_handling', label: 'Ball Handling', goatScore: 98 },
        { key: 'shooting', label: 'Shooting', goatScore: 85 },
        { key: 'court_vision', label: 'Court Vision', goatScore: 99 },
        { key: 'defense', label: 'Defense', goatScore: 80 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 90 },
        { key: 'leadership', label: 'Leadership', goatScore: 97 },
        { key: 'iq', label: 'Basketball IQ', goatScore: 98 },
        { key: 'finishing', label: 'Finishing', goatScore: 92 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 90 },
        { key: 'consistency', label: 'Consistency', goatScore: 95 },
      ],
    },
    {
      code: 'SG', name: 'Shooting Guard', archetype: 'The Assassin', color: '#EF4444',
      goat: 'Michael Jordan', goatCountry: 'USA',
      radarDimensions: [
        { key: 'scoring', label: 'Scoring', goatScore: 99 },
        { key: 'shooting', label: 'Shooting', goatScore: 95 },
        { key: 'defense', label: 'Defense', goatScore: 99 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 99 },
        { key: 'ball_handling', label: 'Ball Handling', goatScore: 90 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 99 },
        { key: 'iq', label: 'Basketball IQ', goatScore: 96 },
        { key: 'finishing', label: 'Finishing', goatScore: 99 },
        { key: 'leadership', label: 'Leadership', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 97 },
      ],
    },
    {
      code: 'SF', name: 'Small Forward', archetype: 'The Versatile Wing', color: '#10B981',
      goat: 'LeBron James', goatCountry: 'USA',
      radarDimensions: [
        { key: 'scoring', label: 'Scoring', goatScore: 97 },
        { key: 'passing', label: 'Passing', goatScore: 95 },
        { key: 'defense', label: 'Defense', goatScore: 90 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 97 },
        { key: 'iq', label: 'Basketball IQ', goatScore: 99 },
        { key: 'rebounding', label: 'Rebounding', goatScore: 88 },
        { key: 'leadership', label: 'Leadership', goatScore: 98 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 92 },
        { key: 'versatility', label: 'Versatility', goatScore: 99 },
        { key: 'durability', label: 'Durability', goatScore: 96 },
      ],
    },
    {
      code: 'PF', name: 'Power Forward', archetype: 'The Enforcer', color: '#F59E0B',
      goat: 'Tim Duncan', goatCountry: 'USA',
      radarDimensions: [
        { key: 'post_game', label: 'Post Game', goatScore: 98 },
        { key: 'rebounding', label: 'Rebounding', goatScore: 95 },
        { key: 'defense', label: 'Defense', goatScore: 99 },
        { key: 'shooting', label: 'Mid-Range', goatScore: 90 },
        { key: 'iq', label: 'Basketball IQ', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'leadership', label: 'Leadership', goatScore: 95 },
        { key: 'toughness', label: 'Toughness', goatScore: 97 },
        { key: 'footwork', label: 'Footwork', goatScore: 98 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 95 },
      ],
    },
    {
      code: 'C', name: 'Center', archetype: 'The Anchor', color: '#8B5CF6',
      goat: 'Kareem Abdul-Jabbar', goatCountry: 'USA',
      radarDimensions: [
        { key: 'post_game', label: 'Post Game', goatScore: 99 },
        { key: 'rebounding', label: 'Rebounding', goatScore: 95 },
        { key: 'shot_blocking', label: 'Shot Blocking', goatScore: 97 },
        { key: 'scoring', label: 'Scoring', goatScore: 99 },
        { key: 'defense', label: 'Defense', goatScore: 95 },
        { key: 'durability', label: 'Durability', goatScore: 99 },
        { key: 'iq', label: 'Basketball IQ', goatScore: 95 },
        { key: 'footwork', label: 'Footwork', goatScore: 97 },
        { key: 'toughness', label: 'Toughness', goatScore: 93 },
        { key: 'consistency', label: 'Consistency', goatScore: 98 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'points', label: 'PTS', type: 'number' },
    { key: 'rebounds', label: 'REB', type: 'number' },
    { key: 'assists', label: 'AST', type: 'number' },
    { key: 'steals', label: 'STL', type: 'number' },
    { key: 'blocks', label: 'BLK', type: 'number' },
    { key: 'turnovers', label: 'TO', type: 'number' },
    { key: 'fg_pct', label: 'FG%', type: 'percent' },
    { key: 'three_pct', label: '3P%', type: 'percent' },
    { key: 'ft_pct', label: 'FT%', type: 'percent' },
    { key: 'minutes', label: 'MIN', type: 'number' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '6-13', color: '#F59E0B',
      philosophy: 'Focus on fun, fundamentals, and multi-sport participation. Build love for the game.',
      keyFocus: ['Ball handling basics', 'Shooting form', 'Teamwork', 'Sportsmanship'],
      restrictions: ['No weight training under 14', 'Limited game schedule', 'Equal playing time'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '14-18', color: '#10B981',
      philosophy: 'Develop position-specific skills, compete at school and club level.',
      keyFocus: ['Position skills', 'Game IQ', 'Strength conditioning', 'Film study'],
      restrictions: ['Balanced academics', 'Injury prevention focus'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-23', color: '#3B82F6',
      philosophy: 'Compete at highest amateur level, prepare for professional transition.',
      keyFocus: ['Advanced tactics', 'Professional habits', 'Strength & conditioning', 'Leadership'],
      restrictions: ['NCAA/USports eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '19+', color: '#8B5CF6',
      philosophy: 'Peak performance, longevity, and impact at the highest level.',
      keyFocus: ['Elite skill refinement', 'Recovery science', 'Mental performance', 'Legacy building'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    PG: [
      { name: 'The Orchestrator', description: 'Pass-first floor general who controls tempo', traits: ['Vision', 'Patience', 'Communication'] },
      { name: 'The Scorer', description: 'Score-first guard who creates own shot', traits: ['Aggression', 'Shot creation', 'Confidence'] },
      { name: 'The Disruptor', description: 'Defensive-minded guard who forces turnovers', traits: ['Anticipation', 'Speed', 'Energy'] },
      { name: 'The Hybrid', description: 'Two-way guard equally effective on both ends', traits: ['Versatility', 'Adaptability', 'IQ'] },
    ],
    SG: [
      { name: 'The Sniper', description: 'Catch-and-shoot specialist with range', traits: ['Accuracy', 'Movement', 'Quick release'] },
      { name: 'The Slasher', description: 'Attacks the rim relentlessly', traits: ['Explosiveness', 'Finishing', 'Contact'] },
      { name: 'The Two-Way', description: 'Elite defender who also scores', traits: ['Tenacity', 'Footwork', 'Discipline'] },
      { name: 'The Creator', description: 'Combo guard who creates for self and others', traits: ['Handles', 'Vision', 'Craft'] },
    ],
    SF: [
      { name: 'The Point Forward', description: 'Initiates offense from the wing', traits: ['Playmaking', 'Size', 'Court vision'] },
      { name: 'The 3-and-D', description: 'Shoots threes and locks down opponents', traits: ['Shooting', 'Physicality', 'Discipline'] },
      { name: 'The Scorer', description: 'Multi-level scoring threat', traits: ['Shot variety', 'Footwork', 'Strength'] },
      { name: 'The Swiss Army', description: 'Does everything at a high level', traits: ['Versatility', 'IQ', 'Motor'] },
    ],
    PF: [
      { name: 'The Stretch', description: 'Floor-spacing big who shoots from range', traits: ['Shooting', 'Mobility', 'Spacing'] },
      { name: 'The Bruiser', description: 'Physical paint presence', traits: ['Strength', 'Rebounding', 'Toughness'] },
      { name: 'The Playmaker', description: 'High-post facilitator with vision', traits: ['Passing', 'Skill', 'IQ'] },
      { name: 'The Rim Runner', description: 'Runs the floor and finishes at the rim', traits: ['Speed', 'Athleticism', 'Energy'] },
    ],
    C: [
      { name: 'The Rim Protector', description: 'Anchors defense and alters shots', traits: ['Shot blocking', 'Timing', 'Presence'] },
      { name: 'The Post Scorer', description: 'Dominant back-to-basket scorer', traits: ['Footwork', 'Touch', 'Strength'] },
      { name: 'The Modern Big', description: 'Shoots, passes, and switches on defense', traits: ['Versatility', 'Skill', 'Mobility'] },
      { name: 'The Rebounder', description: 'Controls the glass on both ends', traits: ['Positioning', 'Effort', 'Toughness'] },
    ],
  },
  personaQuiz: [
    {
      question: 'When your team is down late, what do you want to do?',
      options: [
        { text: 'Take over and score', archetypes: { PG: 'The Scorer', SG: 'The Slasher', SF: 'The Scorer', PF: 'The Stretch', C: 'The Post Scorer' } },
        { text: 'Set up the best shooter', archetypes: { PG: 'The Orchestrator', SG: 'The Creator', SF: 'The Point Forward', PF: 'The Playmaker', C: 'The Modern Big' } },
        { text: 'Lock down on defense', archetypes: { PG: 'The Disruptor', SG: 'The Two-Way', SF: 'The 3-and-D', PF: 'The Bruiser', C: 'The Rim Protector' } },
        { text: 'Do whatever the team needs', archetypes: { PG: 'The Hybrid', SG: 'The Creator', SF: 'The Swiss Army', PF: 'The Rim Runner', C: 'The Rebounder' } },
      ],
    },
    {
      question: 'What part of practice do you enjoy most?',
      options: [
        { text: 'Shooting drills', archetypes: { PG: 'The Scorer', SG: 'The Sniper', SF: 'The 3-and-D', PF: 'The Stretch', C: 'The Modern Big' } },
        { text: 'Scrimmages', archetypes: { PG: 'The Orchestrator', SG: 'The Creator', SF: 'The Point Forward', PF: 'The Playmaker', C: 'The Post Scorer' } },
        { text: 'Defensive drills', archetypes: { PG: 'The Disruptor', SG: 'The Two-Way', SF: 'The 3-and-D', PF: 'The Bruiser', C: 'The Rim Protector' } },
        { text: 'Conditioning', archetypes: { PG: 'The Hybrid', SG: 'The Slasher', SF: 'The Swiss Army', PF: 'The Rim Runner', C: 'The Rebounder' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The engine that makes everything go', archetypes: { PG: 'The Orchestrator', SG: 'The Creator', SF: 'The Point Forward', PF: 'The Playmaker', C: 'The Modern Big' } },
        { text: 'A bucket getter', archetypes: { PG: 'The Scorer', SG: 'The Sniper', SF: 'The Scorer', PF: 'The Stretch', C: 'The Post Scorer' } },
        { text: 'A defensive stopper', archetypes: { PG: 'The Disruptor', SG: 'The Two-Way', SF: 'The 3-and-D', PF: 'The Bruiser', C: 'The Rim Protector' } },
        { text: 'The hardest worker on the team', archetypes: { PG: 'The Hybrid', SG: 'The Slasher', SF: 'The Swiss Army', PF: 'The Rim Runner', C: 'The Rebounder' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Assists', archetypes: { PG: 'The Orchestrator', SG: 'The Creator', SF: 'The Point Forward', PF: 'The Playmaker', C: 'The Modern Big' } },
        { text: 'Points', archetypes: { PG: 'The Scorer', SG: 'The Sniper', SF: 'The Scorer', PF: 'The Stretch', C: 'The Post Scorer' } },
        { text: 'Steals/Blocks', archetypes: { PG: 'The Disruptor', SG: 'The Two-Way', SF: 'The 3-and-D', PF: 'The Bruiser', C: 'The Rim Protector' } },
        { text: 'Plus/Minus', archetypes: { PG: 'The Hybrid', SG: 'The Slasher', SF: 'The Swiss Army', PF: 'The Rim Runner', C: 'The Rebounder' } },
      ],
    },
  ],
  drills: [
    { name: 'Mikan Drill', position: 'C', difficulty: 2, description: 'Alternating layups from each side of the basket', equipment: ['Basketball', 'Hoop'] },
    { name: 'Three-Point Circuit', position: 'SG', difficulty: 3, description: '5 spots around the arc, 3 makes per spot', equipment: ['Basketball', 'Hoop'] },
    { name: 'Full-Court Dribble Series', position: 'PG', difficulty: 3, description: 'Crossover, behind-back, spin moves full court', equipment: ['Basketball'] },
    { name: 'Defensive Slides', position: 'ALL', difficulty: 2, description: 'Lateral slides baseline to baseline', equipment: [] },
    { name: 'Post Footwork Series', position: 'PF', difficulty: 4, description: 'Drop step, face-up, up-and-under', equipment: ['Basketball', 'Hoop'] },
    { name: 'Wing Isolation', position: 'SF', difficulty: 4, description: 'Triple threat moves from the wing', equipment: ['Basketball', 'Hoop', 'Cones'] },
  ],
  benchmarks: [
    { name: 'Vertical Jump', unit: 'inches', youth: 16, school: 24, university: 30, professional: 36 },
    { name: 'Lane Agility', unit: 'seconds', youth: 14, school: 12, university: 11, professional: 10.5 },
    { name: '3/4 Court Sprint', unit: 'seconds', youth: 4.5, school: 3.8, university: 3.4, professional: 3.1 },
    { name: 'Bench Press (185)', unit: 'reps', youth: 0, school: 3, university: 8, professional: 12 },
  ],
};
