import type { SportConfig } from './types';

export const cricket: SportConfig = {
  id: 'cricket',
  name: 'Cricket',
  emoji: '\u{1F3CF}',
  color: '#059669',
  courtType: 'pitch',
  positions: [
    {
      code: 'OB', name: 'Opening Batter', archetype: 'The Trailblazer', color: '#EF4444',
      goat: 'Sachin Tendulkar', goatCountry: 'India',
      radarDimensions: [
        { key: 'technique', label: 'Technique', goatScore: 99 },
        { key: 'temperament', label: 'Temperament', goatScore: 97 },
        { key: 'shot_selection', label: 'Shot Selection', goatScore: 98 },
        { key: 'against_pace', label: 'Against Pace', goatScore: 98 },
        { key: 'against_spin', label: 'Against Spin', goatScore: 97 },
        { key: 'running', label: 'Running Between Wickets', goatScore: 90 },
        { key: 'concentration', label: 'Concentration', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 95 },
        { key: 'durability', label: 'Durability', goatScore: 98 },
      ],
    },
    {
      code: 'TO', name: 'Top Order Batter', archetype: 'The Accumulator', color: '#3B82F6',
      goat: 'Virat Kohli', goatCountry: 'India',
      radarDimensions: [
        { key: 'run_scoring', label: 'Run Scoring', goatScore: 99 },
        { key: 'chase_master', label: 'Chase Mastery', goatScore: 99 },
        { key: 'technique', label: 'Technique', goatScore: 96 },
        { key: 'fitness', label: 'Fitness', goatScore: 98 },
        { key: 'running', label: 'Running Between Wickets', goatScore: 97 },
        { key: 'shot_selection', label: 'Shot Selection', goatScore: 95 },
        { key: 'consistency', label: 'Consistency', goatScore: 98 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 96 },
        { key: 'leadership', label: 'Leadership', goatScore: 95 },
        { key: 'adaptability', label: 'Adaptability', goatScore: 97 },
      ],
    },
    {
      code: 'MO', name: 'Middle Order Batter', archetype: 'The Finisher', color: '#10B981',
      goat: 'MS Dhoni', goatCountry: 'India',
      radarDimensions: [
        { key: 'finishing', label: 'Finishing', goatScore: 99 },
        { key: 'power_hitting', label: 'Power Hitting', goatScore: 96 },
        { key: 'composure', label: 'Composure Under Pressure', goatScore: 99 },
        { key: 'innovation', label: 'Innovation', goatScore: 97 },
        { key: 'running', label: 'Running Between Wickets', goatScore: 95 },
        { key: 'against_spin', label: 'Against Spin', goatScore: 94 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 99 },
        { key: 'leadership', label: 'Leadership', goatScore: 98 },
        { key: 'adaptability', label: 'Adaptability', goatScore: 96 },
        { key: 'cricket_iq', label: 'Cricket IQ', goatScore: 99 },
      ],
    },
    {
      code: 'FB', name: 'Fast Bowler', archetype: 'The Enforcer', color: '#F59E0B',
      goat: 'Dale Steyn', goatCountry: 'South Africa',
      radarDimensions: [
        { key: 'pace', label: 'Pace', goatScore: 98 },
        { key: 'swing', label: 'Swing', goatScore: 97 },
        { key: 'seam', label: 'Seam Movement', goatScore: 96 },
        { key: 'accuracy', label: 'Accuracy', goatScore: 95 },
        { key: 'bouncer', label: 'Bouncer', goatScore: 94 },
        { key: 'yorker', label: 'Yorker', goatScore: 93 },
        { key: 'fitness', label: 'Fitness', goatScore: 92 },
        { key: 'wicket_taking', label: 'Wicket-Taking', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 95 },
        { key: 'aggression', label: 'Aggression', goatScore: 97 },
      ],
    },
    {
      code: 'SB', name: 'Spin Bowler', archetype: 'The Deceiver', color: '#8B5CF6',
      goat: 'Shane Warne', goatCountry: 'Australia',
      radarDimensions: [
        { key: 'turn', label: 'Turn', goatScore: 99 },
        { key: 'variation', label: 'Variations', goatScore: 99 },
        { key: 'flight', label: 'Flight', goatScore: 98 },
        { key: 'accuracy', label: 'Accuracy', goatScore: 95 },
        { key: 'deception', label: 'Deception', goatScore: 99 },
        { key: 'wicket_taking', label: 'Wicket-Taking', goatScore: 98 },
        { key: 'cricket_iq', label: 'Cricket IQ', goatScore: 97 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 96 },
        { key: 'consistency', label: 'Consistency', goatScore: 94 },
        { key: 'leadership', label: 'Leadership', goatScore: 92 },
      ],
    },
    {
      code: 'AR', name: 'All-Rounder', archetype: 'The Complete Cricketer', color: '#EC4899',
      goat: 'Sir Garfield Sobers', goatCountry: 'West Indies',
      radarDimensions: [
        { key: 'batting', label: 'Batting', goatScore: 97 },
        { key: 'bowling', label: 'Bowling', goatScore: 95 },
        { key: 'fielding', label: 'Fielding', goatScore: 93 },
        { key: 'versatility', label: 'Versatility', goatScore: 99 },
        { key: 'fitness', label: 'Fitness', goatScore: 94 },
        { key: 'cricket_iq', label: 'Cricket IQ', goatScore: 97 },
        { key: 'leadership', label: 'Leadership', goatScore: 95 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 94 },
        { key: 'adaptability', label: 'Adaptability', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
      ],
    },
    {
      code: 'WK', name: 'Wicketkeeper', archetype: 'The Gloveman', color: '#F97316',
      goat: 'Adam Gilchrist', goatCountry: 'Australia',
      radarDimensions: [
        { key: 'glovework', label: 'Glovework', goatScore: 93 },
        { key: 'batting', label: 'Batting', goatScore: 97 },
        { key: 'power_hitting', label: 'Power Hitting', goatScore: 98 },
        { key: 'reflexes', label: 'Reflexes', goatScore: 95 },
        { key: 'standing_up', label: 'Standing Up to Spinners', goatScore: 90 },
        { key: 'stumpings', label: 'Stumpings', goatScore: 88 },
        { key: 'leadership', label: 'Leadership', goatScore: 92 },
        { key: 'fitness', label: 'Fitness', goatScore: 94 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 96 },
        { key: 'cricket_iq', label: 'Cricket IQ', goatScore: 95 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'runs', label: 'RUNS', type: 'number' },
    { key: 'balls_faced', label: 'BF', type: 'number' },
    { key: 'fours', label: '4s', type: 'number' },
    { key: 'sixes', label: '6s', type: 'number' },
    { key: 'strike_rate', label: 'SR', type: 'decimal' },
    { key: 'wickets', label: 'W', type: 'number' },
    { key: 'overs', label: 'O', type: 'decimal' },
    { key: 'runs_conceded', label: 'RC', type: 'number' },
    { key: 'economy', label: 'ECON', type: 'decimal' },
    { key: 'catches', label: 'CT', type: 'number' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '6-13', color: '#F59E0B',
      philosophy: 'Learn the basics of batting, bowling, and fielding through fun-first coaching.',
      keyFocus: ['Batting grip and stance', 'Bowling action', 'Catching', 'Running between wickets'],
      restrictions: ['Modified pitch lengths (Cricket Canada)', 'Soft-ball cricket options', 'Equal participation'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '14-18', color: '#10B981',
      philosophy: 'Develop skills for competition in Cricket Canada age-group and school leagues.',
      keyFocus: ['Role specialization', 'Game awareness', 'Fitness development', 'Match play'],
      restrictions: ['Academic balance', 'Bowling workload guidelines', 'Cricket Canada pathway'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-23', color: '#3B82F6',
      philosophy: 'Compete at club and national age-group level while pursuing higher education.',
      keyFocus: ['Advanced technique', 'Match strategy', 'Physical conditioning', 'Mental preparation'],
      restrictions: ['Academic requirements', 'Cricket Canada selection protocols'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '17+', color: '#8B5CF6',
      philosophy: 'Represent Canada internationally and compete in franchise cricket worldwide.',
      keyFocus: ['Elite skill refinement', 'Multi-format preparation', 'Recovery science', 'Leadership'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    OB: [
      { name: 'The Trailblazer', description: 'Attacks from ball one and puts pressure on the bowlers', traits: ['Aggression', 'Shot-making', 'Intent'] },
      { name: 'The Anchor', description: 'Patient opener who bats deep and builds the innings', traits: ['Patience', 'Technique', 'Concentration'] },
      { name: 'The Technician', description: 'Textbook technique against both pace and spin', traits: ['Technique', 'Footwork', 'Shot selection'] },
      { name: 'The Dasher', description: 'Explosive opener who takes the powerplay by storm', traits: ['Power', 'Timing', 'Fearlessness'] },
    ],
    TO: [
      { name: 'The Accumulator', description: 'Rotates strike and builds big totals with minimal risk', traits: ['Running', 'Placement', 'Consistency'] },
      { name: 'The Chase Master', description: 'Specializes in chasing down targets under pressure', traits: ['Composure', 'Pacing', 'Clutch'] },
      { name: 'The Strokemaker', description: 'Elegant batter with a wide range of shots', traits: ['Timing', 'Shot variety', 'Elegance'] },
      { name: 'The Modern Batter', description: 'Innovative player comfortable across all formats', traits: ['Innovation', 'Adaptability', 'Power'] },
    ],
    MO: [
      { name: 'The Finisher', description: 'Closes out innings with explosive hitting', traits: ['Power hitting', 'Composure', 'Death overs'] },
      { name: 'The Stabilizer', description: 'Rebuilds the innings after early wickets fall', traits: ['Patience', 'Temperament', 'Resilience'] },
      { name: 'The Innovator', description: 'Invents shots and keeps bowlers guessing', traits: ['Creativity', 'Unorthodoxy', 'Flair'] },
      { name: 'The Captain\'s Knock', description: 'Delivers match-winning performances in big moments', traits: ['Clutch', 'Leadership', 'Experience'] },
    ],
    FB: [
      { name: 'The Express', description: 'Raw pace that intimidates batters', traits: ['Speed', 'Bounce', 'Aggression'] },
      { name: 'The Swing King', description: 'Moves the ball both ways through the air', traits: ['Swing', 'Seam position', 'Accuracy'] },
      { name: 'The Death Bowler', description: 'Nails yorkers at the death and controls the finish', traits: ['Yorker', 'Variations', 'Composure'] },
      { name: 'The Workhorse', description: 'Bowls long spells and maintains pressure all day', traits: ['Stamina', 'Consistency', 'Durability'] },
    ],
    SB: [
      { name: 'The Deceiver', description: 'Bamboozles batters with turn, flight, and variation', traits: ['Turn', 'Variations', 'Deception'] },
      { name: 'The Miser', description: 'Miserly spinner who dries up runs and creates pressure', traits: ['Accuracy', 'Economy', 'Discipline'] },
      { name: 'The Attacking Spinner', description: 'Spins hard and bowls for wickets every ball', traits: ['Turn', 'Aggression', 'Wicket-taking'] },
      { name: 'The Match Winner', description: 'Delivers breakthrough wickets in crucial moments', traits: ['Clutch', 'Big match temperament', 'IQ'] },
    ],
    AR: [
      { name: 'The Complete Cricketer', description: 'Equally match-winning with bat and ball', traits: ['Versatility', 'Skill', 'Impact'] },
      { name: 'The Batting All-Rounder', description: 'Primarily a batter who contributes useful overs', traits: ['Batting', 'Part-time bowling', 'Flexibility'] },
      { name: 'The Bowling All-Rounder', description: 'Primarily a bowler who can bat in the lower order', traits: ['Bowling', 'Handy bat', 'Depth'] },
      { name: 'The Utility Player', description: 'Does a bit of everything and fills any gap in the team', traits: ['Adaptability', 'Fielding', 'Team play'] },
    ],
    WK: [
      { name: 'The Gloveman', description: 'Elite keeper whose glovework is his primary skill', traits: ['Glovework', 'Reflexes', 'Footwork'] },
      { name: 'The Keeper-Batter', description: 'Explosive batter who can change a game from behind the stumps', traits: ['Batting', 'Power', 'Aggression'] },
      { name: 'The Quiet Operator', description: 'Efficient, reliable keeper who rarely makes mistakes', traits: ['Consistency', 'Focus', 'Reliability'] },
      { name: 'The Captain\'s Ally', description: 'Vocal keeper who helps the captain with field placements and tactics', traits: ['Communication', 'IQ', 'Leadership'] },
    ],
  },
  personaQuiz: [
    {
      question: 'Your team needs 20 off the last 2 overs. What do you want to do?',
      options: [
        { text: 'Smash sixes to win it quickly', archetypes: { OB: 'The Dasher', TO: 'The Modern Batter', MO: 'The Finisher', FB: 'The Express', SB: 'The Attacking Spinner', AR: 'The Complete Cricketer', WK: 'The Keeper-Batter' } },
        { text: 'Rotate strike and pick the right balls', archetypes: { OB: 'The Anchor', TO: 'The Accumulator', MO: 'The Stabilizer', FB: 'The Workhorse', SB: 'The Miser', AR: 'The Utility Player', WK: 'The Quiet Operator' } },
        { text: 'Stay calm and time the chase perfectly', archetypes: { OB: 'The Technician', TO: 'The Chase Master', MO: 'The Captain\'s Knock', FB: 'The Death Bowler', SB: 'The Match Winner', AR: 'The Batting All-Rounder', WK: 'The Captain\'s Ally' } },
        { text: 'Play smart strokes to the boundary', archetypes: { OB: 'The Trailblazer', TO: 'The Strokemaker', MO: 'The Innovator', FB: 'The Swing King', SB: 'The Deceiver', AR: 'The Bowling All-Rounder', WK: 'The Gloveman' } },
      ],
    },
    {
      question: 'What part of practice do you enjoy most?',
      options: [
        { text: 'Batting in the nets', archetypes: { OB: 'The Trailblazer', TO: 'The Strokemaker', MO: 'The Finisher', FB: 'The Express', SB: 'The Attacking Spinner', AR: 'The Batting All-Rounder', WK: 'The Keeper-Batter' } },
        { text: 'Bowling spells', archetypes: { OB: 'The Anchor', TO: 'The Accumulator', MO: 'The Stabilizer', FB: 'The Swing King', SB: 'The Deceiver', AR: 'The Bowling All-Rounder', WK: 'The Gloveman' } },
        { text: 'Match simulation', archetypes: { OB: 'The Technician', TO: 'The Chase Master', MO: 'The Captain\'s Knock', FB: 'The Death Bowler', SB: 'The Match Winner', AR: 'The Complete Cricketer', WK: 'The Captain\'s Ally' } },
        { text: 'Fielding and fitness', archetypes: { OB: 'The Dasher', TO: 'The Modern Batter', MO: 'The Innovator', FB: 'The Workhorse', SB: 'The Miser', AR: 'The Utility Player', WK: 'The Quiet Operator' } },
      ],
    },
    {
      question: 'Your captain describes you as:',
      options: [
        { text: 'The match winner', archetypes: { OB: 'The Trailblazer', TO: 'The Chase Master', MO: 'The Finisher', FB: 'The Express', SB: 'The Match Winner', AR: 'The Complete Cricketer', WK: 'The Keeper-Batter' } },
        { text: 'The most reliable player', archetypes: { OB: 'The Anchor', TO: 'The Accumulator', MO: 'The Stabilizer', FB: 'The Workhorse', SB: 'The Miser', AR: 'The Utility Player', WK: 'The Quiet Operator' } },
        { text: 'The most skilled player', archetypes: { OB: 'The Technician', TO: 'The Strokemaker', MO: 'The Innovator', FB: 'The Swing King', SB: 'The Deceiver', AR: 'The Bowling All-Rounder', WK: 'The Gloveman' } },
        { text: 'The leader of the group', archetypes: { OB: 'The Dasher', TO: 'The Modern Batter', MO: 'The Captain\'s Knock', FB: 'The Death Bowler', SB: 'The Attacking Spinner', AR: 'The Batting All-Rounder', WK: 'The Captain\'s Ally' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Runs scored', archetypes: { OB: 'The Trailblazer', TO: 'The Chase Master', MO: 'The Finisher', FB: 'The Express', SB: 'The Attacking Spinner', AR: 'The Batting All-Rounder', WK: 'The Keeper-Batter' } },
        { text: 'Wickets taken', archetypes: { OB: 'The Anchor', TO: 'The Accumulator', MO: 'The Stabilizer', FB: 'The Swing King', SB: 'The Deceiver', AR: 'The Bowling All-Rounder', WK: 'The Gloveman' } },
        { text: 'Strike rate', archetypes: { OB: 'The Dasher', TO: 'The Modern Batter', MO: 'The Innovator', FB: 'The Death Bowler', SB: 'The Match Winner', AR: 'The Complete Cricketer', WK: 'The Captain\'s Ally' } },
        { text: 'Batting average', archetypes: { OB: 'The Technician', TO: 'The Strokemaker', MO: 'The Captain\'s Knock', FB: 'The Workhorse', SB: 'The Miser', AR: 'The Utility Player', WK: 'The Quiet Operator' } },
      ],
    },
  ],
  drills: [
    { name: 'Throwdowns', position: 'OB', difficulty: 3, description: 'Face rapid throwdowns to sharpen reflexes and timing against pace', equipment: ['Bat', 'Balls', 'Helmet'] },
    { name: 'Spin Bowling Reps', position: 'SB', difficulty: 4, description: 'Bowl 6-over spells focusing on turn, flight, and variation', equipment: ['Balls', 'Stumps'] },
    { name: 'Yorker Practice', position: 'FB', difficulty: 4, description: 'Land yorkers at a target cone on a good length repeatedly', equipment: ['Balls', 'Stumps', 'Cones'] },
    { name: 'Slip Catching', position: 'WK', difficulty: 3, description: 'React to edges off a bat with catching cradle or live nets', equipment: ['Balls', 'Slip cradle'] },
    { name: 'Power Hitting Drill', position: 'MO', difficulty: 4, description: 'Hit sixes off full-length balls targeting specific zones', equipment: ['Bat', 'Balls', 'Helmet'] },
    { name: 'All-Round Scenario', position: 'AR', difficulty: 4, description: 'Bat 5 overs then bowl 5 overs in match simulation', equipment: ['Full kit', 'Balls', 'Stumps'] },
  ],
  benchmarks: [
    { name: '2km Time Trial', unit: 'minutes', youth: 12, school: 9.5, university: 8, professional: 7 },
    { name: 'Bowling Speed', unit: 'km/h', youth: 80, school: 110, university: 130, professional: 145 },
    { name: '20m Sprint', unit: 'seconds', youth: 4.5, school: 3.5, university: 3.0, professional: 2.7 },
    { name: 'Throwing Distance', unit: 'meters', youth: 30, school: 55, university: 70, professional: 80 },
  ],
};
