import type { SportConfig } from './types';

export const football: SportConfig = {
  id: 'football',
  name: 'Football',
  emoji: '\u{1F3C8}',
  color: '#7C3AED',
  courtType: 'field',
  positions: [
    {
      code: 'QB', name: 'Quarterback', archetype: 'The Field General', color: '#EF4444',
      goat: 'Tom Brady', goatCountry: 'USA',
      radarDimensions: [
        { key: 'arm_strength', label: 'Arm Strength', goatScore: 90 },
        { key: 'accuracy', label: 'Accuracy', goatScore: 97 },
        { key: 'decision_making', label: 'Decision Making', goatScore: 99 },
        { key: 'pocket_presence', label: 'Pocket Presence', goatScore: 99 },
        { key: 'leadership', label: 'Leadership', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 99 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 99 },
        { key: 'durability', label: 'Durability', goatScore: 98 },
        { key: 'pre_snap_read', label: 'Pre-Snap Read', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 98 },
      ],
    },
    {
      code: 'RB', name: 'Running Back', archetype: 'The Workhorse', color: '#F59E0B',
      goat: 'Barry Sanders', goatCountry: 'USA',
      radarDimensions: [
        { key: 'elusiveness', label: 'Elusiveness', goatScore: 99 },
        { key: 'vision', label: 'Vision', goatScore: 99 },
        { key: 'speed', label: 'Speed', goatScore: 96 },
        { key: 'agility', label: 'Agility', goatScore: 99 },
        { key: 'power', label: 'Power', goatScore: 85 },
        { key: 'receiving', label: 'Receiving', goatScore: 88 },
        { key: 'blocking', label: 'Pass Protection', goatScore: 82 },
        { key: 'durability', label: 'Durability', goatScore: 90 },
        { key: 'explosiveness', label: 'Explosiveness', goatScore: 99 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 95 },
      ],
    },
    {
      code: 'WR', name: 'Wide Receiver', archetype: 'The Playmaker', color: '#3B82F6',
      goat: 'Jerry Rice', goatCountry: 'USA',
      radarDimensions: [
        { key: 'route_running', label: 'Route Running', goatScore: 99 },
        { key: 'hands', label: 'Hands', goatScore: 98 },
        { key: 'speed', label: 'Speed', goatScore: 93 },
        { key: 'yac', label: 'YAC Ability', goatScore: 95 },
        { key: 'blocking', label: 'Blocking', goatScore: 92 },
        { key: 'durability', label: 'Durability', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 97 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 96 },
        { key: 'work_ethic', label: 'Work Ethic', goatScore: 99 },
      ],
    },
    {
      code: 'TE', name: 'Tight End', archetype: 'The Mismatch', color: '#10B981',
      goat: 'Tony Gonzalez', goatCountry: 'USA',
      radarDimensions: [
        { key: 'receiving', label: 'Receiving', goatScore: 98 },
        { key: 'blocking', label: 'Blocking', goatScore: 88 },
        { key: 'route_running', label: 'Route Running', goatScore: 95 },
        { key: 'hands', label: 'Hands', goatScore: 97 },
        { key: 'yac', label: 'YAC Ability', goatScore: 92 },
        { key: 'size', label: 'Size Advantage', goatScore: 95 },
        { key: 'durability', label: 'Durability', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 97 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 94 },
        { key: 'red_zone', label: 'Red Zone Threat', goatScore: 96 },
      ],
    },
    {
      code: 'OL', name: 'Offensive Lineman', archetype: 'The Anchor', color: '#64748B',
      goat: 'Anthony Munoz', goatCountry: 'USA',
      radarDimensions: [
        { key: 'pass_protection', label: 'Pass Protection', goatScore: 99 },
        { key: 'run_blocking', label: 'Run Blocking', goatScore: 98 },
        { key: 'strength', label: 'Strength', goatScore: 97 },
        { key: 'footwork', label: 'Footwork', goatScore: 98 },
        { key: 'technique', label: 'Technique', goatScore: 99 },
        { key: 'durability', label: 'Durability', goatScore: 95 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 96 },
        { key: 'consistency', label: 'Consistency', goatScore: 98 },
        { key: 'toughness', label: 'Toughness', goatScore: 97 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 94 },
      ],
    },
    {
      code: 'DL', name: 'Defensive Lineman', archetype: 'The Disruptor', color: '#DC2626',
      goat: 'Reggie White', goatCountry: 'USA',
      radarDimensions: [
        { key: 'pass_rush', label: 'Pass Rush', goatScore: 99 },
        { key: 'strength', label: 'Strength', goatScore: 98 },
        { key: 'speed', label: 'Speed', goatScore: 94 },
        { key: 'technique', label: 'Technique', goatScore: 97 },
        { key: 'run_defense', label: 'Run Defense', goatScore: 96 },
        { key: 'motor', label: 'Motor', goatScore: 98 },
        { key: 'toughness', label: 'Toughness', goatScore: 97 },
        { key: 'durability', label: 'Durability', goatScore: 95 },
        { key: 'leadership', label: 'Leadership', goatScore: 96 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 93 },
      ],
    },
    {
      code: 'LB', name: 'Linebacker', archetype: 'The Enforcer', color: '#F97316',
      goat: 'Lawrence Taylor', goatCountry: 'USA',
      radarDimensions: [
        { key: 'pass_rush', label: 'Pass Rush', goatScore: 99 },
        { key: 'tackling', label: 'Tackling', goatScore: 97 },
        { key: 'speed', label: 'Speed', goatScore: 95 },
        { key: 'instincts', label: 'Instincts', goatScore: 99 },
        { key: 'intimidation', label: 'Intimidation', goatScore: 99 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 97 },
        { key: 'run_defense', label: 'Run Defense', goatScore: 95 },
        { key: 'coverage', label: 'Coverage', goatScore: 85 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 94 },
        { key: 'motor', label: 'Motor', goatScore: 98 },
      ],
    },
    {
      code: 'CB', name: 'Cornerback', archetype: 'The Island', color: '#8B5CF6',
      goat: 'Deion Sanders', goatCountry: 'USA',
      radarDimensions: [
        { key: 'coverage', label: 'Coverage', goatScore: 99 },
        { key: 'speed', label: 'Speed', goatScore: 99 },
        { key: 'ball_skills', label: 'Ball Skills', goatScore: 98 },
        { key: 'agility', label: 'Agility', goatScore: 97 },
        { key: 'man_coverage', label: 'Man Coverage', goatScore: 99 },
        { key: 'zone_coverage', label: 'Zone Coverage', goatScore: 90 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 96 },
        { key: 'clutch', label: 'Playmaking', goatScore: 98 },
        { key: 'tackling', label: 'Tackling', goatScore: 75 },
        { key: 'confidence', label: 'Confidence', goatScore: 99 },
      ],
    },
    {
      code: 'S', name: 'Safety', archetype: 'The Hawk', color: '#06B6D4',
      goat: 'Ed Reed', goatCountry: 'USA',
      radarDimensions: [
        { key: 'range', label: 'Range', goatScore: 99 },
        { key: 'ball_skills', label: 'Ball Skills', goatScore: 99 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 99 },
        { key: 'tackling', label: 'Tackling', goatScore: 88 },
        { key: 'coverage', label: 'Coverage', goatScore: 97 },
        { key: 'instincts', label: 'Instincts', goatScore: 99 },
        { key: 'playmaking', label: 'Playmaking', goatScore: 99 },
        { key: 'speed', label: 'Speed', goatScore: 93 },
        { key: 'versatility', label: 'Versatility', goatScore: 96 },
        { key: 'leadership', label: 'Leadership', goatScore: 95 },
      ],
    },
    {
      code: 'K', name: 'Kicker', archetype: 'The Closer', color: '#EC4899',
      goat: 'Adam Vinatieri', goatCountry: 'USA',
      radarDimensions: [
        { key: 'accuracy', label: 'Accuracy', goatScore: 97 },
        { key: 'leg_strength', label: 'Leg Strength', goatScore: 92 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
        { key: 'range', label: 'Range', goatScore: 93 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 99 },
        { key: 'weather', label: 'Weather Kicking', goatScore: 97 },
        { key: 'kickoffs', label: 'Kickoffs', goatScore: 90 },
        { key: 'durability', label: 'Durability', goatScore: 98 },
        { key: 'composure', label: 'Composure', goatScore: 99 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'pass_yards', label: 'PYDS', type: 'number' },
    { key: 'rush_yards', label: 'RYDS', type: 'number' },
    { key: 'touchdowns', label: 'TD', type: 'number' },
    { key: 'interceptions', label: 'INT', type: 'number' },
    { key: 'receptions', label: 'REC', type: 'number' },
    { key: 'tackles', label: 'TKL', type: 'number' },
    { key: 'sacks', label: 'SCK', type: 'number' },
    { key: 'fumbles', label: 'FUM', type: 'number' },
    { key: 'field_goals', label: 'FG', type: 'text' },
    { key: 'passer_rating', label: 'RTG', type: 'decimal' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '6-13', color: '#F59E0B',
      philosophy: 'Build athleticism and love for the game through flag football and fundamentals.',
      keyFocus: ['Flag football', 'Running and catching', 'Tackling safety', 'Teamwork'],
      restrictions: ['Flag only under 10 (Football Canada)', 'No full contact under 12', 'Limited contact practices'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '14-18', color: '#10B981',
      philosophy: 'Develop position skills and compete in high school football across Canada.',
      keyFocus: ['Position specialization', 'Film study', 'Strength & conditioning', 'Game planning'],
      restrictions: ['Academic eligibility', 'Football Canada concussion protocols', 'Practice contact limits'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-24', color: '#3B82F6',
      philosophy: 'Compete at USports level and develop toward CFL or professional opportunity.',
      keyFocus: ['Advanced scheme mastery', 'Elite conditioning', 'Pro-style preparation', 'Leadership'],
      restrictions: ['USports eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '21+', color: '#8B5CF6',
      philosophy: 'Perform at the highest level in the CFL or NFL.',
      keyFocus: ['Elite scheme execution', 'Recovery & longevity', 'Mental performance', 'Championship preparation'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    QB: [
      { name: 'The Field General', description: 'Master tactician who dissects defenses from the pocket', traits: ['IQ', 'Leadership', 'Accuracy'] },
      { name: 'The Gunslinger', description: 'Big arm who makes fearless throws down the field', traits: ['Arm strength', 'Confidence', 'Risk-taking'] },
      { name: 'The Dual Threat', description: 'Dangerous with both arm and legs', traits: ['Mobility', 'Arm talent', 'Improvisation'] },
      { name: 'The Game Manager', description: 'Efficient passer who protects the ball and moves the chains', traits: ['Decision making', 'Consistency', 'Composure'] },
    ],
    RB: [
      { name: 'The Workhorse', description: 'Bell-cow back who carries the load every game', traits: ['Durability', 'Power', 'Consistency'] },
      { name: 'The Elusive Back', description: 'Makes defenders miss in tight spaces', traits: ['Agility', 'Vision', 'Elusiveness'] },
      { name: 'The Speed Back', description: 'Home-run threat who takes any play to the house', traits: ['Speed', 'Breakaway ability', 'Acceleration'] },
      { name: 'The Receiving Back', description: 'Dual threat out of the backfield as a receiver', traits: ['Hands', 'Route running', 'Versatility'] },
    ],
    WR: [
      { name: 'The Playmaker', description: 'Complete receiver who wins at every level of the route tree', traits: ['Route running', 'Hands', 'IQ'] },
      { name: 'The Deep Threat', description: 'Stretches the field with elite speed', traits: ['Speed', 'Tracking', 'Acceleration'] },
      { name: 'The Possession WR', description: 'Reliable chain mover on third down', traits: ['Hands', 'Route precision', 'Toughness'] },
      { name: 'The YAC Monster', description: 'Dangerous with the ball in hands after the catch', traits: ['YAC', 'Elusiveness', 'Power'] },
    ],
    TE: [
      { name: 'The Mismatch', description: 'Too big for DBs, too fast for linebackers', traits: ['Size', 'Speed', 'Matchup nightmare'] },
      { name: 'The Blocker', description: 'Dominant in-line blocker who moves defenders', traits: ['Blocking', 'Strength', 'Toughness'] },
      { name: 'The Move TE', description: 'Lines up everywhere and creates mismatches', traits: ['Route running', 'Versatility', 'Hands'] },
      { name: 'The Red Zone Weapon', description: 'Go-to target inside the 20', traits: ['Size', 'Hands', 'Contested catches'] },
    ],
    OL: [
      { name: 'The Anchor', description: 'Immovable pass protector who never gets beat', traits: ['Strength', 'Technique', 'Balance'] },
      { name: 'The Mauler', description: 'Dominant run blocker who creates holes', traits: ['Power', 'Aggression', 'Drive blocking'] },
      { name: 'The Technician', description: 'Wins with footwork and hand placement', traits: ['Footwork', 'Hands', 'Technique'] },
      { name: 'The Athletic OL', description: 'Pulls, traps, and gets to the second level', traits: ['Athleticism', 'Speed', 'Mobility'] },
    ],
    DL: [
      { name: 'The Disruptor', description: 'Wrecks game plans with constant pressure', traits: ['Pass rush', 'Motor', 'Technique'] },
      { name: 'The Nose Tackle', description: 'Clogs the middle and eats double teams', traits: ['Strength', 'Size', 'Anchor'] },
      { name: 'The Edge Rusher', description: 'Speed-to-power pass rusher off the edge', traits: ['Speed', 'Bend', 'Explosiveness'] },
      { name: 'The Versatile DL', description: 'Plays multiple positions along the line', traits: ['Versatility', 'IQ', 'Technique'] },
    ],
    LB: [
      { name: 'The Enforcer', description: 'Violent hitter who sets the tone for the defense', traits: ['Hitting', 'Aggression', 'Intimidation'] },
      { name: 'The Coverage LB', description: 'Athletic linebacker who can cover tight ends and backs', traits: ['Coverage', 'Speed', 'Instincts'] },
      { name: 'The Quarterback of the D', description: 'Calls the plays and aligns the defense', traits: ['IQ', 'Leadership', 'Communication'] },
      { name: 'The Blitzer', description: 'Elite pass rusher from the linebacker position', traits: ['Pass rush', 'Speed', 'Timing'] },
    ],
    CB: [
      { name: 'The Island', description: 'Locks down one side of the field in man coverage', traits: ['Man coverage', 'Speed', 'Confidence'] },
      { name: 'The Ball Hawk', description: 'Creates turnovers with elite ball skills', traits: ['Ball skills', 'Instincts', 'Playmaking'] },
      { name: 'The Slot Corner', description: 'Quick and tough defender who works the inside', traits: ['Agility', 'Toughness', 'Quickness'] },
      { name: 'The Physical Corner', description: 'Press coverage specialist who disrupts timing', traits: ['Press', 'Physicality', 'Length'] },
    ],
    S: [
      { name: 'The Hawk', description: 'Patrols the deep middle and jumps routes', traits: ['Range', 'Ball skills', 'Instincts'] },
      { name: 'The Enforcer Safety', description: 'Hard-hitting safety who plays the run and the pass', traits: ['Hitting', 'Tackling', 'Physicality'] },
      { name: 'The Hybrid', description: 'Plays safety, slot corner, and linebacker', traits: ['Versatility', 'Athleticism', 'IQ'] },
      { name: 'The Centerfielder', description: 'Deep-half safety with elite range and instincts', traits: ['Range', 'Speed', 'Read ability'] },
    ],
    K: [
      { name: 'The Closer', description: 'Makes the kicks that win championships', traits: ['Clutch', 'Composure', 'Accuracy'] },
      { name: 'The Leg', description: 'Booming kicks with 55+ yard range', traits: ['Leg strength', 'Range', 'Power'] },
      { name: 'The Automatic', description: 'Rarely misses inside 50 yards', traits: ['Consistency', 'Accuracy', 'Technique'] },
      { name: 'The Weapon', description: 'Pins touchbacks on kickoffs and nails field goals', traits: ['Kickoffs', 'Versatility', 'Power'] },
    ],
  },
  personaQuiz: [
    {
      question: 'Fourth quarter, game on the line. What do you want to do?',
      options: [
        { text: 'Make the game-winning play with the ball', archetypes: { QB: 'The Dual Threat', RB: 'The Elusive Back', WR: 'The Playmaker', TE: 'The Mismatch', OL: 'The Athletic OL', DL: 'The Edge Rusher', LB: 'The Blitzer', CB: 'The Ball Hawk', S: 'The Hawk', K: 'The Closer' } },
        { text: 'Lead the team down the field methodically', archetypes: { QB: 'The Field General', RB: 'The Workhorse', WR: 'The Possession WR', TE: 'The Move TE', OL: 'The Technician', DL: 'The Versatile DL', LB: 'The Quarterback of the D', CB: 'The Island', S: 'The Hybrid', K: 'The Automatic' } },
        { text: 'Make a big defensive stop', archetypes: { QB: 'The Game Manager', RB: 'The Receiving Back', WR: 'The YAC Monster', TE: 'The Blocker', OL: 'The Anchor', DL: 'The Disruptor', LB: 'The Enforcer', CB: 'The Physical Corner', S: 'The Enforcer Safety', K: 'The Weapon' } },
        { text: 'Hit a deep ball or take a shot', archetypes: { QB: 'The Gunslinger', RB: 'The Speed Back', WR: 'The Deep Threat', TE: 'The Red Zone Weapon', OL: 'The Mauler', DL: 'The Nose Tackle', LB: 'The Coverage LB', CB: 'The Slot Corner', S: 'The Centerfielder', K: 'The Leg' } },
      ],
    },
    {
      question: 'What part of practice do you enjoy most?',
      options: [
        { text: 'Live scrimmage and competition', archetypes: { QB: 'The Dual Threat', RB: 'The Elusive Back', WR: 'The YAC Monster', TE: 'The Mismatch', OL: 'The Mauler', DL: 'The Disruptor', LB: 'The Enforcer', CB: 'The Physical Corner', S: 'The Enforcer Safety', K: 'The Closer' } },
        { text: 'Film study and walk-throughs', archetypes: { QB: 'The Field General', RB: 'The Receiving Back', WR: 'The Possession WR', TE: 'The Move TE', OL: 'The Technician', DL: 'The Versatile DL', LB: 'The Quarterback of the D', CB: 'The Island', S: 'The Hawk', K: 'The Automatic' } },
        { text: 'Individual drills and technique work', archetypes: { QB: 'The Game Manager', RB: 'The Workhorse', WR: 'The Playmaker', TE: 'The Blocker', OL: 'The Anchor', DL: 'The Nose Tackle', LB: 'The Coverage LB', CB: 'The Slot Corner', S: 'The Hybrid', K: 'The Weapon' } },
        { text: 'Speed work and conditioning', archetypes: { QB: 'The Gunslinger', RB: 'The Speed Back', WR: 'The Deep Threat', TE: 'The Red Zone Weapon', OL: 'The Athletic OL', DL: 'The Edge Rusher', LB: 'The Blitzer', CB: 'The Ball Hawk', S: 'The Centerfielder', K: 'The Leg' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The smartest player on the field', archetypes: { QB: 'The Field General', RB: 'The Receiving Back', WR: 'The Possession WR', TE: 'The Move TE', OL: 'The Technician', DL: 'The Versatile DL', LB: 'The Quarterback of the D', CB: 'The Island', S: 'The Hawk', K: 'The Automatic' } },
        { text: 'The most explosive athlete', archetypes: { QB: 'The Dual Threat', RB: 'The Speed Back', WR: 'The Deep Threat', TE: 'The Mismatch', OL: 'The Athletic OL', DL: 'The Edge Rusher', LB: 'The Blitzer', CB: 'The Ball Hawk', S: 'The Centerfielder', K: 'The Leg' } },
        { text: 'The toughest player on the roster', archetypes: { QB: 'The Gunslinger', RB: 'The Workhorse', WR: 'The YAC Monster', TE: 'The Blocker', OL: 'The Mauler', DL: 'The Nose Tackle', LB: 'The Enforcer', CB: 'The Physical Corner', S: 'The Enforcer Safety', K: 'The Weapon' } },
        { text: 'The most reliable player game after game', archetypes: { QB: 'The Game Manager', RB: 'The Elusive Back', WR: 'The Playmaker', TE: 'The Red Zone Weapon', OL: 'The Anchor', DL: 'The Disruptor', LB: 'The Coverage LB', CB: 'The Slot Corner', S: 'The Hybrid', K: 'The Closer' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Touchdowns', archetypes: { QB: 'The Dual Threat', RB: 'The Speed Back', WR: 'The Deep Threat', TE: 'The Mismatch', OL: 'The Athletic OL', DL: 'The Edge Rusher', LB: 'The Blitzer', CB: 'The Ball Hawk', S: 'The Hawk', K: 'The Closer' } },
        { text: 'Yards', archetypes: { QB: 'The Gunslinger', RB: 'The Workhorse', WR: 'The Playmaker', TE: 'The Move TE', OL: 'The Mauler', DL: 'The Disruptor', LB: 'The Enforcer', CB: 'The Physical Corner', S: 'The Enforcer Safety', K: 'The Leg' } },
        { text: 'Completion % / Win rate', archetypes: { QB: 'The Field General', RB: 'The Receiving Back', WR: 'The Possession WR', TE: 'The Blocker', OL: 'The Technician', DL: 'The Versatile DL', LB: 'The Quarterback of the D', CB: 'The Island', S: 'The Hybrid', K: 'The Automatic' } },
        { text: 'Tackles / Sacks', archetypes: { QB: 'The Game Manager', RB: 'The Elusive Back', WR: 'The YAC Monster', TE: 'The Red Zone Weapon', OL: 'The Anchor', DL: 'The Nose Tackle', LB: 'The Coverage LB', CB: 'The Slot Corner', S: 'The Centerfielder', K: 'The Weapon' } },
      ],
    },
  ],
  drills: [
    { name: 'Dropback & Throw', position: 'QB', difficulty: 3, description: '3-step, 5-step, and 7-step drops with throws to moving targets', equipment: ['Footballs', 'Targets', 'Cones'] },
    { name: 'Cone Agility Series', position: 'RB', difficulty: 3, description: 'Pro agility, L-drill, and gauntlet ball-security drill', equipment: ['Cones', 'Football'] },
    { name: 'Route Tree', position: 'WR', difficulty: 4, description: 'Run all 9 routes in the route tree against air and press coverage', equipment: ['Footballs', 'Cones'] },
    { name: 'Pass Rush Moves', position: 'DL', difficulty: 4, description: 'Speed rush, bull rush, spin, and rip moves off the edge', equipment: ['Pass rush pad', 'Sled'] },
    { name: 'Backpedal & Break', position: 'CB', difficulty: 3, description: 'Backpedal, flip hips, and break on the ball in zone and man', equipment: ['Footballs', 'Cones'] },
    { name: 'Field Goal Range', position: 'K', difficulty: 3, description: 'Kick from 20, 30, 40, and 50+ yards with hold from both hashes', equipment: ['Footballs', 'Tee', 'Uprights'] },
  ],
  benchmarks: [
    { name: '40-Yard Dash', unit: 'seconds', youth: 6.5, school: 5.2, university: 4.7, professional: 4.4 },
    { name: 'Bench Press (225)', unit: 'reps', youth: 0, school: 5, university: 15, professional: 25 },
    { name: 'Vertical Jump', unit: 'inches', youth: 18, school: 28, university: 34, professional: 40 },
    { name: 'Broad Jump', unit: 'inches', youth: 72, school: 96, university: 112, professional: 124 },
  ],
};
