import type { SportConfig } from './types';

export const hockey: SportConfig = {
  id: 'hockey',
  name: 'Hockey',
  emoji: '\u{1F3D2}',
  color: '#0EA5E9',
  courtType: 'rink',
  positions: [
    {
      code: 'C', name: 'Center', archetype: 'The Playmaker', color: '#3B82F6',
      goat: 'Wayne Gretzky', goatCountry: 'Canada',
      radarDimensions: [
        { key: 'faceoffs', label: 'Faceoffs', goatScore: 88 },
        { key: 'scoring', label: 'Scoring', goatScore: 99 },
        { key: 'playmaking', label: 'Playmaking', goatScore: 99 },
        { key: 'skating', label: 'Skating', goatScore: 88 },
        { key: 'hockey_iq', label: 'Hockey IQ', goatScore: 99 },
        { key: 'defensive_play', label: 'Defensive Play', goatScore: 80 },
        { key: 'puck_control', label: 'Puck Control', goatScore: 98 },
        { key: 'leadership', label: 'Leadership', goatScore: 97 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 96 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
      ],
    },
    {
      code: 'LW', name: 'Left Wing', archetype: 'The Sniper', color: '#EF4444',
      goat: 'Alex Ovechkin', goatCountry: 'Russia',
      radarDimensions: [
        { key: 'shooting', label: 'Shooting', goatScore: 99 },
        { key: 'power', label: 'Power', goatScore: 98 },
        { key: 'scoring', label: 'Scoring', goatScore: 99 },
        { key: 'physicality', label: 'Physicality', goatScore: 96 },
        { key: 'skating', label: 'Skating', goatScore: 88 },
        { key: 'positioning', label: 'Positioning', goatScore: 95 },
        { key: 'one_timer', label: 'One-Timer', goatScore: 99 },
        { key: 'durability', label: 'Durability', goatScore: 97 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 94 },
        { key: 'hockey_iq', label: 'Hockey IQ', goatScore: 90 },
      ],
    },
    {
      code: 'RW', name: 'Right Wing', archetype: 'The Finisher', color: '#10B981',
      goat: 'Gordie Howe', goatCountry: 'Canada',
      radarDimensions: [
        { key: 'scoring', label: 'Scoring', goatScore: 97 },
        { key: 'physicality', label: 'Physicality', goatScore: 99 },
        { key: 'toughness', label: 'Toughness', goatScore: 99 },
        { key: 'shooting', label: 'Shooting', goatScore: 94 },
        { key: 'skating', label: 'Skating', goatScore: 90 },
        { key: 'durability', label: 'Durability', goatScore: 99 },
        { key: 'puck_control', label: 'Puck Control', goatScore: 93 },
        { key: 'leadership', label: 'Leadership', goatScore: 95 },
        { key: 'hockey_iq', label: 'Hockey IQ', goatScore: 94 },
        { key: 'versatility', label: 'Versatility', goatScore: 96 },
      ],
    },
    {
      code: 'D', name: 'Defenseman', archetype: 'The Guardian', color: '#F59E0B',
      goat: 'Bobby Orr', goatCountry: 'Canada',
      radarDimensions: [
        { key: 'skating', label: 'Skating', goatScore: 99 },
        { key: 'defensive_play', label: 'Defensive Play', goatScore: 95 },
        { key: 'offensive_rush', label: 'Offensive Rush', goatScore: 99 },
        { key: 'puck_control', label: 'Puck Control', goatScore: 97 },
        { key: 'physicality', label: 'Physicality', goatScore: 90 },
        { key: 'shot_blocking', label: 'Shot Blocking', goatScore: 85 },
        { key: 'hockey_iq', label: 'Hockey IQ', goatScore: 98 },
        { key: 'transition', label: 'Transition Play', goatScore: 99 },
        { key: 'leadership', label: 'Leadership', goatScore: 94 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 95 },
      ],
    },
    {
      code: 'G', name: 'Goaltender', archetype: 'The Wall', color: '#8B5CF6',
      goat: 'Patrick Roy', goatCountry: 'Canada',
      radarDimensions: [
        { key: 'reflexes', label: 'Reflexes', goatScore: 98 },
        { key: 'positioning', label: 'Positioning', goatScore: 97 },
        { key: 'glove_hand', label: 'Glove Hand', goatScore: 96 },
        { key: 'rebound_control', label: 'Rebound Control', goatScore: 94 },
        { key: 'puck_handling', label: 'Puck Handling', goatScore: 90 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 95 },
        { key: 'durability', label: 'Durability', goatScore: 93 },
        { key: 'hockey_iq', label: 'Hockey IQ', goatScore: 96 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'goals', label: 'G', type: 'number' },
    { key: 'assists', label: 'A', type: 'number' },
    { key: 'plus_minus', label: '+/-', type: 'number' },
    { key: 'shots', label: 'SOG', type: 'number' },
    { key: 'hits', label: 'HIT', type: 'number' },
    { key: 'blocks', label: 'BLK', type: 'number' },
    { key: 'toi', label: 'TOI', type: 'time' },
    { key: 'saves', label: 'SV', type: 'number' },
    { key: 'gaa', label: 'GAA', type: 'decimal' },
    { key: 'save_pct', label: 'SV%', type: 'percent' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '5-12', color: '#F59E0B',
      philosophy: 'Learn to skate, love the game, and develop basic puck skills through play.',
      keyFocus: ['Skating fundamentals', 'Puck handling basics', 'Small-area games', 'Team play'],
      restrictions: ['No body checking under 13 (Hockey Canada)', 'Limited ice time', 'Equal playing time'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '13-18', color: '#10B981',
      philosophy: 'Develop position-specific skills and compete in minor hockey and high school leagues.',
      keyFocus: ['Position skills', 'System play', 'Power skating', 'Off-ice training'],
      restrictions: ['Academic balance', 'Concussion protocols', 'Hockey Canada age rules'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-24', color: '#3B82F6',
      philosophy: 'Compete at USports/NCAA level and build professional-caliber habits.',
      keyFocus: ['Advanced tactics', 'Video analysis', 'Strength & conditioning', 'Mental game'],
      restrictions: ['USports/NCAA eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '18+', color: '#8B5CF6',
      philosophy: 'Perform at the peak level in the NHL, AHL, or international competition.',
      keyFocus: ['Elite skill refinement', 'Recovery & longevity', 'Leadership', 'Playoff performance'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    C: [
      { name: 'The Playmaker', description: 'Pass-first center who drives possession and sets up goals', traits: ['Vision', 'Faceoffs', 'Patience'] },
      { name: 'The Power Center', description: 'Physical, two-way force who dominates both zones', traits: ['Strength', 'Defensive play', 'Grinding'] },
      { name: 'The Sniper', description: 'Goal-scoring center with an elite release', traits: ['Shooting', 'Accuracy', 'Quick release'] },
      { name: 'The Two-Way', description: 'Selke-caliber center trusted in all situations', traits: ['Positioning', 'Hockey IQ', 'Versatility'] },
    ],
    LW: [
      { name: 'The Rocket', description: 'Speed demon who attacks off the rush', traits: ['Speed', 'Acceleration', 'Finishing'] },
      { name: 'The Sniper', description: 'Pure goal scorer with a lethal one-timer', traits: ['Shooting', 'Positioning', 'Release'] },
      { name: 'The Power Forward', description: 'Physical winger who drives to the net', traits: ['Strength', 'Net presence', 'Toughness'] },
      { name: 'The Grinder', description: 'Relentless forechecker who wears opponents down', traits: ['Work ethic', 'Physicality', 'Energy'] },
    ],
    RW: [
      { name: 'The Finisher', description: 'Elite goal scorer with a deadly wrister', traits: ['Wrist shot', 'Timing', 'Accuracy'] },
      { name: 'The Playmaker', description: 'Creative winger who generates chances', traits: ['Vision', 'Passing', 'Puck control'] },
      { name: 'The Enforcer', description: 'Physical presence who protects teammates', traits: ['Toughness', 'Intimidation', 'Heart'] },
      { name: 'The Two-Way Wing', description: 'Responsible winger trusted on the penalty kill', traits: ['Defensive IQ', 'Backchecking', 'Discipline'] },
    ],
    D: [
      { name: 'The Offensive D', description: 'Quarterback from the blue line who rushes the puck', traits: ['Skating', 'Passing', 'Offensive instinct'] },
      { name: 'The Shutdown D', description: 'Locks down top lines and blocks shots', traits: ['Positioning', 'Gap control', 'Shot blocking'] },
      { name: 'The Physical D', description: 'Punishing hitter who clears the crease', traits: ['Physicality', 'Toughness', 'Strength'] },
      { name: 'The Puck Mover', description: 'Smooth skater who transitions play quickly', traits: ['First pass', 'Skating', 'Composure'] },
    ],
    G: [
      { name: 'The Butterfly', description: 'Technical goalie who seals the ice with positioning', traits: ['Positioning', 'Technique', 'Consistency'] },
      { name: 'The Athletic', description: 'Highlight-reel goalie who makes desperation saves', traits: ['Reflexes', 'Flexibility', 'Recovery'] },
      { name: 'The Hybrid', description: 'Blends butterfly with stand-up to read plays', traits: ['Adaptability', 'IQ', 'Anticipation'] },
      { name: 'The Competitor', description: 'Fiery goalie who elevates in pressure moments', traits: ['Mental toughness', 'Focus', 'Clutch'] },
    ],
  },
  personaQuiz: [
    {
      question: 'The game is tied in the third period. What do you want to do?',
      options: [
        { text: 'Wire a shot top corner', archetypes: { C: 'The Sniper', LW: 'The Sniper', RW: 'The Finisher', D: 'The Offensive D', G: 'The Athletic' } },
        { text: 'Set up a teammate for the winner', archetypes: { C: 'The Playmaker', LW: 'The Rocket', RW: 'The Playmaker', D: 'The Puck Mover', G: 'The Hybrid' } },
        { text: 'Lock it down defensively', archetypes: { C: 'The Two-Way', LW: 'The Grinder', RW: 'The Two-Way Wing', D: 'The Shutdown D', G: 'The Butterfly' } },
        { text: 'Throw a big hit to spark the team', archetypes: { C: 'The Power Center', LW: 'The Power Forward', RW: 'The Enforcer', D: 'The Physical D', G: 'The Competitor' } },
      ],
    },
    {
      question: 'What part of practice do you enjoy most?',
      options: [
        { text: 'Shooting drills', archetypes: { C: 'The Sniper', LW: 'The Sniper', RW: 'The Finisher', D: 'The Offensive D', G: 'The Athletic' } },
        { text: 'Passing and breakout plays', archetypes: { C: 'The Playmaker', LW: 'The Rocket', RW: 'The Playmaker', D: 'The Puck Mover', G: 'The Hybrid' } },
        { text: 'Defensive-zone coverage', archetypes: { C: 'The Two-Way', LW: 'The Grinder', RW: 'The Two-Way Wing', D: 'The Shutdown D', G: 'The Butterfly' } },
        { text: 'Battle drills and scrimmages', archetypes: { C: 'The Power Center', LW: 'The Power Forward', RW: 'The Enforcer', D: 'The Physical D', G: 'The Competitor' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The most skilled player on the ice', archetypes: { C: 'The Playmaker', LW: 'The Sniper', RW: 'The Playmaker', D: 'The Offensive D', G: 'The Hybrid' } },
        { text: 'A pure goal scorer', archetypes: { C: 'The Sniper', LW: 'The Rocket', RW: 'The Finisher', D: 'The Puck Mover', G: 'The Athletic' } },
        { text: 'The most reliable player on the team', archetypes: { C: 'The Two-Way', LW: 'The Grinder', RW: 'The Two-Way Wing', D: 'The Shutdown D', G: 'The Butterfly' } },
        { text: 'Someone opponents hate to play against', archetypes: { C: 'The Power Center', LW: 'The Power Forward', RW: 'The Enforcer', D: 'The Physical D', G: 'The Competitor' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Goals', archetypes: { C: 'The Sniper', LW: 'The Sniper', RW: 'The Finisher', D: 'The Offensive D', G: 'The Athletic' } },
        { text: 'Assists', archetypes: { C: 'The Playmaker', LW: 'The Rocket', RW: 'The Playmaker', D: 'The Puck Mover', G: 'The Hybrid' } },
        { text: 'Plus/Minus', archetypes: { C: 'The Two-Way', LW: 'The Grinder', RW: 'The Two-Way Wing', D: 'The Shutdown D', G: 'The Butterfly' } },
        { text: 'Hits', archetypes: { C: 'The Power Center', LW: 'The Power Forward', RW: 'The Enforcer', D: 'The Physical D', G: 'The Competitor' } },
      ],
    },
  ],
  drills: [
    { name: 'Power Skating Circuit', position: 'ALL', difficulty: 3, description: 'Crossovers, transitions, and edge work through pylons', equipment: ['Skates', 'Pylons'] },
    { name: 'One-Timer Reps', position: 'LW', difficulty: 4, description: 'Receive passes from the half-wall and fire one-timers', equipment: ['Stick', 'Pucks', 'Net'] },
    { name: 'Breakout Patterns', position: 'D', difficulty: 3, description: 'Practice 5 breakout options under forechecking pressure', equipment: ['Pucks', 'Full team'] },
    { name: 'Faceoff Technique', position: 'C', difficulty: 3, description: 'Win draws using tie-up, forehand sweep, and backhand pull', equipment: ['Stick', 'Pucks'] },
    { name: 'Butterfly Recovery', position: 'G', difficulty: 4, description: 'Drop into butterfly and push across crease for second save', equipment: ['Goalie gear', 'Pucks', 'Net'] },
    { name: 'Net-Front Battle', position: 'RW', difficulty: 4, description: 'Tip and screen drills in front of the crease', equipment: ['Stick', 'Pucks', 'Net'] },
  ],
  benchmarks: [
    { name: 'Top Skating Speed', unit: 'km/h', youth: 22, school: 30, university: 35, professional: 40 },
    { name: 'Slap Shot Speed', unit: 'km/h', youth: 60, school: 95, university: 120, professional: 155 },
    { name: 'Agility Drill', unit: 'seconds', youth: 35, school: 28, university: 24, professional: 20 },
    { name: 'Bench Press (135)', unit: 'reps', youth: 0, school: 5, university: 12, professional: 20 },
  ],
};
