import type { SportConfig } from './types';

export const soccer: SportConfig = {
  id: 'soccer',
  name: 'Soccer',
  emoji: '\u26BD',
  color: '#16A34A',
  courtType: 'pitch',
  positions: [
    {
      code: 'GK', name: 'Goalkeeper', archetype: 'The Last Line', color: '#F59E0B',
      goat: 'Gianluigi Buffon', goatCountry: 'Italy',
      radarDimensions: [
        { key: 'shot_stopping', label: 'Shot Stopping', goatScore: 99 },
        { key: 'positioning', label: 'Positioning', goatScore: 98 },
        { key: 'distribution', label: 'Distribution', goatScore: 88 },
        { key: 'command', label: 'Command of Area', goatScore: 97 },
        { key: 'reflexes', label: 'Reflexes', goatScore: 96 },
        { key: 'one_on_one', label: 'One-on-One', goatScore: 95 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 97 },
        { key: 'leadership', label: 'Leadership', goatScore: 98 },
        { key: 'durability', label: 'Durability', goatScore: 99 },
      ],
    },
    {
      code: 'CB', name: 'Center Back', archetype: 'The Rock', color: '#8B5CF6',
      goat: 'Paolo Maldini', goatCountry: 'Italy',
      radarDimensions: [
        { key: 'tackling', label: 'Tackling', goatScore: 99 },
        { key: 'positioning', label: 'Positioning', goatScore: 99 },
        { key: 'aerial', label: 'Aerial Duels', goatScore: 93 },
        { key: 'passing', label: 'Passing', goatScore: 90 },
        { key: 'composure', label: 'Composure', goatScore: 98 },
        { key: 'reading', label: 'Reading the Game', goatScore: 99 },
        { key: 'leadership', label: 'Leadership', goatScore: 97 },
        { key: 'speed', label: 'Recovery Speed', goatScore: 88 },
        { key: 'consistency', label: 'Consistency', goatScore: 98 },
        { key: 'durability', label: 'Durability', goatScore: 97 },
      ],
    },
    {
      code: 'LB', name: 'Left Back', archetype: 'The Overlapper', color: '#06B6D4',
      goat: 'Roberto Carlos', goatCountry: 'Brazil',
      radarDimensions: [
        { key: 'crossing', label: 'Crossing', goatScore: 97 },
        { key: 'pace', label: 'Pace', goatScore: 96 },
        { key: 'tackling', label: 'Tackling', goatScore: 85 },
        { key: 'shooting', label: 'Shooting', goatScore: 92 },
        { key: 'stamina', label: 'Stamina', goatScore: 97 },
        { key: 'dribbling', label: 'Dribbling', goatScore: 88 },
        { key: 'positioning', label: 'Positioning', goatScore: 82 },
        { key: 'strength', label: 'Strength', goatScore: 94 },
        { key: 'attacking_runs', label: 'Attacking Runs', goatScore: 96 },
        { key: 'delivery', label: 'Set Piece Delivery', goatScore: 95 },
      ],
    },
    {
      code: 'RB', name: 'Right Back', archetype: 'The Engine', color: '#10B981',
      goat: 'Cafu', goatCountry: 'Brazil',
      radarDimensions: [
        { key: 'stamina', label: 'Stamina', goatScore: 99 },
        { key: 'crossing', label: 'Crossing', goatScore: 93 },
        { key: 'tackling', label: 'Tackling', goatScore: 88 },
        { key: 'pace', label: 'Pace', goatScore: 95 },
        { key: 'positioning', label: 'Positioning', goatScore: 90 },
        { key: 'leadership', label: 'Leadership', goatScore: 96 },
        { key: 'attacking_runs', label: 'Attacking Runs', goatScore: 95 },
        { key: 'consistency', label: 'Consistency', goatScore: 94 },
        { key: 'dribbling', label: 'Dribbling', goatScore: 87 },
        { key: 'composure', label: 'Composure', goatScore: 92 },
      ],
    },
    {
      code: 'DM', name: 'Defensive Midfielder', archetype: 'The Shield', color: '#64748B',
      goat: 'Claude Makelele', goatCountry: 'France',
      radarDimensions: [
        { key: 'interceptions', label: 'Interceptions', goatScore: 99 },
        { key: 'tackling', label: 'Tackling', goatScore: 97 },
        { key: 'positioning', label: 'Positioning', goatScore: 99 },
        { key: 'passing', label: 'Passing', goatScore: 88 },
        { key: 'stamina', label: 'Stamina', goatScore: 95 },
        { key: 'reading', label: 'Reading the Game', goatScore: 98 },
        { key: 'composure', label: 'Composure', goatScore: 94 },
        { key: 'discipline', label: 'Discipline', goatScore: 96 },
        { key: 'strength', label: 'Strength', goatScore: 90 },
        { key: 'consistency', label: 'Consistency', goatScore: 95 },
      ],
    },
    {
      code: 'CM', name: 'Central Midfielder', archetype: 'The Metronome', color: '#3B82F6',
      goat: 'Zinedine Zidane', goatCountry: 'France',
      radarDimensions: [
        { key: 'passing', label: 'Passing', goatScore: 98 },
        { key: 'dribbling', label: 'Dribbling', goatScore: 97 },
        { key: 'shooting', label: 'Shooting', goatScore: 90 },
        { key: 'vision', label: 'Vision', goatScore: 98 },
        { key: 'technique', label: 'Technique', goatScore: 99 },
        { key: 'composure', label: 'Composure', goatScore: 96 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 97 },
        { key: 'leadership', label: 'Leadership', goatScore: 93 },
        { key: 'creativity', label: 'Creativity', goatScore: 98 },
        { key: 'aerial', label: 'Aerial Ability', goatScore: 88 },
      ],
    },
    {
      code: 'AM', name: 'Attacking Midfielder', archetype: 'The Playmaker', color: '#EC4899',
      goat: 'Ronaldinho', goatCountry: 'Brazil',
      radarDimensions: [
        { key: 'creativity', label: 'Creativity', goatScore: 99 },
        { key: 'dribbling', label: 'Dribbling', goatScore: 99 },
        { key: 'passing', label: 'Passing', goatScore: 96 },
        { key: 'shooting', label: 'Shooting', goatScore: 90 },
        { key: 'flair', label: 'Flair', goatScore: 99 },
        { key: 'vision', label: 'Vision', goatScore: 97 },
        { key: 'free_kicks', label: 'Free Kicks', goatScore: 95 },
        { key: 'technique', label: 'Technique', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 93 },
        { key: 'entertainment', label: 'Entertainment Value', goatScore: 99 },
      ],
    },
    {
      code: 'LW', name: 'Left Winger', archetype: 'The Dribbler', color: '#F97316',
      goat: 'Cristiano Ronaldo', goatCountry: 'Portugal',
      radarDimensions: [
        { key: 'pace', label: 'Pace', goatScore: 97 },
        { key: 'shooting', label: 'Shooting', goatScore: 98 },
        { key: 'dribbling', label: 'Dribbling', goatScore: 95 },
        { key: 'aerial', label: 'Aerial Ability', goatScore: 98 },
        { key: 'crossing', label: 'Crossing', goatScore: 88 },
        { key: 'strength', label: 'Strength', goatScore: 93 },
        { key: 'finishing', label: 'Finishing', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 97 },
        { key: 'work_rate', label: 'Work Rate', goatScore: 95 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
      ],
    },
    {
      code: 'RW', name: 'Right Winger', archetype: 'The Wizard', color: '#84CC16',
      goat: 'Lionel Messi', goatCountry: 'Argentina',
      radarDimensions: [
        { key: 'dribbling', label: 'Dribbling', goatScore: 99 },
        { key: 'passing', label: 'Passing', goatScore: 97 },
        { key: 'shooting', label: 'Shooting', goatScore: 96 },
        { key: 'vision', label: 'Vision', goatScore: 99 },
        { key: 'finishing', label: 'Finishing', goatScore: 98 },
        { key: 'free_kicks', label: 'Free Kicks', goatScore: 95 },
        { key: 'creativity', label: 'Creativity', goatScore: 99 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 97 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'football_iq', label: 'Football IQ', goatScore: 99 },
      ],
    },
    {
      code: 'CF', name: 'Center Forward', archetype: 'The Target', color: '#DC2626',
      goat: 'Ronaldo Nazario', goatCountry: 'Brazil',
      radarDimensions: [
        { key: 'finishing', label: 'Finishing', goatScore: 99 },
        { key: 'dribbling', label: 'Dribbling', goatScore: 97 },
        { key: 'pace', label: 'Pace', goatScore: 98 },
        { key: 'strength', label: 'Strength', goatScore: 92 },
        { key: 'heading', label: 'Heading', goatScore: 85 },
        { key: 'movement', label: 'Movement', goatScore: 97 },
        { key: 'technique', label: 'Technique', goatScore: 98 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 95 },
        { key: 'creativity', label: 'Creativity', goatScore: 94 },
        { key: 'instinct', label: 'Goal Instinct', goatScore: 99 },
      ],
    },
    {
      code: 'ST', name: 'Striker', archetype: 'The Poacher', color: '#EF4444',
      goat: 'Gerd Muller', goatCountry: 'Germany',
      radarDimensions: [
        { key: 'finishing', label: 'Finishing', goatScore: 99 },
        { key: 'positioning', label: 'Positioning', goatScore: 99 },
        { key: 'heading', label: 'Heading', goatScore: 95 },
        { key: 'movement', label: 'Off-Ball Movement', goatScore: 98 },
        { key: 'instinct', label: 'Goal Instinct', goatScore: 99 },
        { key: 'composure', label: 'Composure', goatScore: 97 },
        { key: 'first_touch', label: 'First Touch', goatScore: 95 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 97 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
        { key: 'anticipation', label: 'Anticipation', goatScore: 99 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'goals', label: 'G', type: 'number' },
    { key: 'assists', label: 'A', type: 'number' },
    { key: 'shots', label: 'SH', type: 'number' },
    { key: 'shots_on_target', label: 'SOT', type: 'number' },
    { key: 'passes', label: 'PAS', type: 'number' },
    { key: 'pass_accuracy', label: 'PA%', type: 'percent' },
    { key: 'tackles', label: 'TKL', type: 'number' },
    { key: 'interceptions', label: 'INT', type: 'number' },
    { key: 'saves', label: 'SV', type: 'number' },
    { key: 'minutes', label: 'MIN', type: 'number' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '4-12', color: '#F59E0B',
      philosophy: 'Fall in love with the ball. Develop technical skills through small-sided games and free play.',
      keyFocus: ['Ball mastery', 'Dribbling', '1v1 skills', 'Small-sided games'],
      restrictions: ['No heading under 12 (Ontario Soccer)', 'Small-sided formats', 'Equal playing time'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '13-18', color: '#10B981',
      philosophy: 'Develop tactical awareness and compete in club, school, and Ontario Soccer leagues.',
      keyFocus: ['Position specialization', 'Tactical systems', 'Physical development', 'Set pieces'],
      restrictions: ['Academic balance', 'Canada Soccer age guidelines', 'Player development pathway'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-23', color: '#3B82F6',
      philosophy: 'Compete at USports/NCAA level and pursue professional pathway via CPL or MLS.',
      keyFocus: ['Advanced tactics', 'Video analysis', 'Professional habits', 'Peak conditioning'],
      restrictions: ['USports/NCAA eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '17+', color: '#8B5CF6',
      philosophy: 'Perform at the highest level in CPL, MLS, or top European leagues.',
      keyFocus: ['Elite tactical execution', 'Recovery science', 'Mental performance', 'International competition'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    GK: [
      { name: 'The Shot Stopper', description: 'Elite reflexes and ability to make the impossible save', traits: ['Reflexes', 'Agility', 'Diving'] },
      { name: 'The Sweeper Keeper', description: 'Commands the box and plays as an extra defender', traits: ['Positioning', 'Distribution', 'Bravery'] },
      { name: 'The Commander', description: 'Vocal leader who organizes the entire defense', traits: ['Leadership', 'Communication', 'Presence'] },
      { name: 'The Wall', description: 'Positionally perfect and almost never beaten', traits: ['Positioning', 'Composure', 'Consistency'] },
    ],
    CB: [
      { name: 'The Rock', description: 'Dominant in the air and immovable in duels', traits: ['Aerial power', 'Strength', 'Tackling'] },
      { name: 'The Ball Player', description: 'Builds play from the back with elite passing', traits: ['Passing', 'Composure', 'Vision'] },
      { name: 'The Reader', description: 'Anticipates danger before it develops', traits: ['Positioning', 'Anticipation', 'IQ'] },
      { name: 'The Stopper', description: 'Aggressive defender who wins every challenge', traits: ['Aggression', 'Tackling', 'Intensity'] },
    ],
    LB: [
      { name: 'The Overlapper', description: 'Bombing runs down the flank to deliver crosses', traits: ['Pace', 'Crossing', 'Stamina'] },
      { name: 'The Inverted FB', description: 'Tucks inside to play as a midfielder in possession', traits: ['Passing', 'Composure', 'Positioning'] },
      { name: 'The Defender', description: 'Stays back and locks down the left side', traits: ['Tackling', 'Positioning', 'Discipline'] },
      { name: 'The Wing Back', description: 'Plays the entire left flank attack and defense', traits: ['Stamina', 'Versatility', 'Work rate'] },
    ],
    RB: [
      { name: 'The Engine', description: 'Tireless runner who patrols the right side all game', traits: ['Stamina', 'Work rate', 'Pace'] },
      { name: 'The Crosser', description: 'Delivers pinpoint crosses from the right side', traits: ['Crossing', 'Delivery', 'Timing'] },
      { name: 'The Lockdown', description: 'Shuts down opposing wingers completely', traits: ['Tackling', 'Marking', 'Discipline'] },
      { name: 'The Playmaking FB', description: 'Creates chances from the fullback position', traits: ['Passing', 'Vision', 'Technique'] },
    ],
    DM: [
      { name: 'The Shield', description: 'Screens the back line and breaks up play', traits: ['Interceptions', 'Positioning', 'Tackling'] },
      { name: 'The Deep Playmaker', description: 'Dictates tempo from deep with elite passing range', traits: ['Passing', 'Vision', 'Composure'] },
      { name: 'The Destroyer', description: 'Wins the ball back aggressively and immediately', traits: ['Aggression', 'Pressing', 'Intensity'] },
      { name: 'The Anchor', description: 'Positionally disciplined midfielder who never leaves the zone', traits: ['Discipline', 'IQ', 'Reliability'] },
    ],
    CM: [
      { name: 'The Metronome', description: 'Controls the tempo and keeps possession ticking', traits: ['Passing', 'Technique', 'Composure'] },
      { name: 'The Box-to-Box', description: 'Covers every blade of grass attack to defense', traits: ['Stamina', 'Versatility', 'Energy'] },
      { name: 'The Maestro', description: 'Unlocks defenses with creative through balls', traits: ['Vision', 'Creativity', 'Technique'] },
      { name: 'The Goal Threat', description: 'Arrives late in the box to score from midfield', traits: ['Timing', 'Shooting', 'Movement'] },
    ],
    AM: [
      { name: 'The Playmaker', description: 'Creates chances with vision and technical brilliance', traits: ['Creativity', 'Vision', 'Passing'] },
      { name: 'The Shadow Striker', description: 'Operates between the lines and finishes clinically', traits: ['Movement', 'Finishing', 'Positioning'] },
      { name: 'The Dribbler', description: 'Takes on defenders and creates magic with the ball', traits: ['Dribbling', 'Flair', 'Skill'] },
      { name: 'The Free Role', description: 'Roams the pitch and appears wherever needed', traits: ['IQ', 'Movement', 'Versatility'] },
    ],
    LW: [
      { name: 'The Wide Threat', description: 'Stretches the pitch with pace and crosses', traits: ['Pace', 'Crossing', 'Direct play'] },
      { name: 'The Inverted Winger', description: 'Cuts inside onto strong foot to shoot or create', traits: ['Cutting inside', 'Shooting', 'Dribbling'] },
      { name: 'The Goal Scorer', description: 'Winger who finishes like a striker', traits: ['Finishing', 'Movement', 'Positioning'] },
      { name: 'The Workhorse Wing', description: 'Tracks back and contributes on both ends', traits: ['Work rate', 'Stamina', 'Discipline'] },
    ],
    RW: [
      { name: 'The Wizard', description: 'Mesmerizing dribbler who beats defenders at will', traits: ['Dribbling', 'Skill', 'Creativity'] },
      { name: 'The Supplier', description: 'Creates chances for teammates with precise delivery', traits: ['Crossing', 'Vision', 'Passing'] },
      { name: 'The Finisher', description: 'Cuts inside and finds the net consistently', traits: ['Shooting', 'Finishing', 'Composure'] },
      { name: 'The Complete Winger', description: 'Scores, creates, and defends from the right', traits: ['Versatility', 'IQ', 'All-round ability'] },
    ],
    CF: [
      { name: 'The Target', description: 'Hold-up play specialist who brings others into the game', traits: ['Strength', 'Link-up play', 'Aerial ability'] },
      { name: 'The Dribbling 9', description: 'Takes on defenders and creates own chances', traits: ['Dribbling', 'Pace', 'Creativity'] },
      { name: 'The False 9', description: 'Drops deep to create overloads in midfield', traits: ['Intelligence', 'Passing', 'Movement'] },
      { name: 'The Fox in the Box', description: 'Clinical finisher who lives for goals in the penalty area', traits: ['Finishing', 'Positioning', 'Instinct'] },
    ],
    ST: [
      { name: 'The Poacher', description: 'Lives off the last defender and finishes with one touch', traits: ['Positioning', 'Instinct', 'Finishing'] },
      { name: 'The Complete Striker', description: 'Can score any type of goal from anywhere', traits: ['Versatility', 'Power', 'Technique'] },
      { name: 'The Pressing Forward', description: 'Leads the press from the front and wins the ball high', traits: ['Work rate', 'Pressing', 'Energy'] },
      { name: 'The Aerial Threat', description: 'Dominant in the air and lethal with headers', traits: ['Heading', 'Positioning', 'Strength'] },
    ],
  },
  personaQuiz: [
    {
      question: 'Your team is losing 1-0 with 10 minutes left. What do you want to do?',
      options: [
        { text: 'Dribble past defenders and score', archetypes: { GK: 'The Shot Stopper', CB: 'The Ball Player', LB: 'The Overlapper', RB: 'The Engine', DM: 'The Deep Playmaker', CM: 'The Maestro', AM: 'The Dribbler', LW: 'The Inverted Winger', RW: 'The Wizard', CF: 'The Dribbling 9', ST: 'The Complete Striker' } },
        { text: 'Play the perfect through ball', archetypes: { GK: 'The Sweeper Keeper', CB: 'The Reader', LB: 'The Inverted FB', RB: 'The Playmaking FB', DM: 'The Shield', CM: 'The Metronome', AM: 'The Playmaker', LW: 'The Wide Threat', RW: 'The Supplier', CF: 'The False 9', ST: 'The Pressing Forward' } },
        { text: 'Get into the box and finish', archetypes: { GK: 'The Wall', CB: 'The Rock', LB: 'The Wing Back', RB: 'The Crosser', DM: 'The Destroyer', CM: 'The Goal Threat', AM: 'The Shadow Striker', LW: 'The Goal Scorer', RW: 'The Finisher', CF: 'The Fox in the Box', ST: 'The Poacher' } },
        { text: 'Do whatever the team needs', archetypes: { GK: 'The Commander', CB: 'The Stopper', LB: 'The Defender', RB: 'The Lockdown', DM: 'The Anchor', CM: 'The Box-to-Box', AM: 'The Free Role', LW: 'The Workhorse Wing', RW: 'The Complete Winger', CF: 'The Target', ST: 'The Aerial Threat' } },
      ],
    },
    {
      question: 'What part of training do you enjoy most?',
      options: [
        { text: 'Finishing drills and shooting practice', archetypes: { GK: 'The Shot Stopper', CB: 'The Rock', LB: 'The Overlapper', RB: 'The Engine', DM: 'The Destroyer', CM: 'The Goal Threat', AM: 'The Shadow Striker', LW: 'The Goal Scorer', RW: 'The Finisher', CF: 'The Fox in the Box', ST: 'The Poacher' } },
        { text: 'Rondos and passing patterns', archetypes: { GK: 'The Sweeper Keeper', CB: 'The Ball Player', LB: 'The Inverted FB', RB: 'The Playmaking FB', DM: 'The Deep Playmaker', CM: 'The Metronome', AM: 'The Playmaker', LW: 'The Wide Threat', RW: 'The Supplier', CF: 'The False 9', ST: 'The Complete Striker' } },
        { text: 'Tactical shape and defensive work', archetypes: { GK: 'The Commander', CB: 'The Reader', LB: 'The Defender', RB: 'The Lockdown', DM: 'The Shield', CM: 'The Box-to-Box', AM: 'The Free Role', LW: 'The Workhorse Wing', RW: 'The Complete Winger', CF: 'The Target', ST: 'The Pressing Forward' } },
        { text: 'Dribbling and skills practice', archetypes: { GK: 'The Wall', CB: 'The Stopper', LB: 'The Wing Back', RB: 'The Crosser', DM: 'The Anchor', CM: 'The Maestro', AM: 'The Dribbler', LW: 'The Inverted Winger', RW: 'The Wizard', CF: 'The Dribbling 9', ST: 'The Aerial Threat' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The most creative player on the team', archetypes: { GK: 'The Sweeper Keeper', CB: 'The Ball Player', LB: 'The Overlapper', RB: 'The Playmaking FB', DM: 'The Deep Playmaker', CM: 'The Maestro', AM: 'The Playmaker', LW: 'The Inverted Winger', RW: 'The Wizard', CF: 'The Dribbling 9', ST: 'The Complete Striker' } },
        { text: 'The most clinical finisher', archetypes: { GK: 'The Shot Stopper', CB: 'The Rock', LB: 'The Wing Back', RB: 'The Crosser', DM: 'The Destroyer', CM: 'The Goal Threat', AM: 'The Shadow Striker', LW: 'The Goal Scorer', RW: 'The Finisher', CF: 'The Fox in the Box', ST: 'The Poacher' } },
        { text: 'The most tactically intelligent', archetypes: { GK: 'The Commander', CB: 'The Reader', LB: 'The Inverted FB', RB: 'The Lockdown', DM: 'The Shield', CM: 'The Metronome', AM: 'The Free Role', LW: 'The Workhorse Wing', RW: 'The Complete Winger', CF: 'The False 9', ST: 'The Pressing Forward' } },
        { text: 'The hardest worker on the pitch', archetypes: { GK: 'The Wall', CB: 'The Stopper', LB: 'The Defender', RB: 'The Engine', DM: 'The Anchor', CM: 'The Box-to-Box', AM: 'The Dribbler', LW: 'The Wide Threat', RW: 'The Supplier', CF: 'The Target', ST: 'The Aerial Threat' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Goals', archetypes: { GK: 'The Shot Stopper', CB: 'The Rock', LB: 'The Overlapper', RB: 'The Engine', DM: 'The Destroyer', CM: 'The Goal Threat', AM: 'The Shadow Striker', LW: 'The Goal Scorer', RW: 'The Finisher', CF: 'The Fox in the Box', ST: 'The Poacher' } },
        { text: 'Assists', archetypes: { GK: 'The Sweeper Keeper', CB: 'The Ball Player', LB: 'The Wing Back', RB: 'The Playmaking FB', DM: 'The Deep Playmaker', CM: 'The Maestro', AM: 'The Playmaker', LW: 'The Wide Threat', RW: 'The Wizard', CF: 'The False 9', ST: 'The Complete Striker' } },
        { text: 'Tackles won', archetypes: { GK: 'The Commander', CB: 'The Stopper', LB: 'The Defender', RB: 'The Lockdown', DM: 'The Shield', CM: 'The Box-to-Box', AM: 'The Free Role', LW: 'The Workhorse Wing', RW: 'The Complete Winger', CF: 'The Target', ST: 'The Pressing Forward' } },
        { text: 'Pass completion rate', archetypes: { GK: 'The Wall', CB: 'The Reader', LB: 'The Inverted FB', RB: 'The Crosser', DM: 'The Anchor', CM: 'The Metronome', AM: 'The Dribbler', LW: 'The Inverted Winger', RW: 'The Supplier', CF: 'The Dribbling 9', ST: 'The Aerial Threat' } },
      ],
    },
  ],
  drills: [
    { name: 'Rondo 5v2', position: 'ALL', difficulty: 3, description: 'Keep possession in a tight circle while 2 defenders press', equipment: ['Ball', 'Cones'] },
    { name: 'Finishing Circuit', position: 'ST', difficulty: 4, description: 'Receive and finish from 6 different positions around the box', equipment: ['Balls', 'Goals', 'Cones'] },
    { name: 'Crossing & Heading', position: 'LW', difficulty: 3, description: 'Deliver crosses from wide areas for attackers to head on goal', equipment: ['Balls', 'Goals'] },
    { name: '1v1 Defending', position: 'CB', difficulty: 3, description: 'Defend in isolated 1v1 scenarios with jockeying and tackling', equipment: ['Balls', 'Cones'] },
    { name: 'Distribution Drill', position: 'GK', difficulty: 3, description: 'Goal kicks, throws, and passes to targets at varying distances', equipment: ['Balls', 'Goals', 'Targets'] },
    { name: 'Pressing Patterns', position: 'DM', difficulty: 4, description: 'Team pressing triggers and recovery runs in 11v11 shape', equipment: ['Balls', 'Cones', 'Bibs'] },
  ],
  benchmarks: [
    { name: 'Beep Test', unit: 'level', youth: 6, school: 9, university: 12, professional: 14 },
    { name: '40m Sprint', unit: 'seconds', youth: 7.2, school: 5.8, university: 5.2, professional: 4.7 },
    { name: 'Vertical Jump', unit: 'cm', youth: 30, school: 45, university: 55, professional: 65 },
    { name: 'Yo-Yo IR1', unit: 'meters', youth: 640, school: 1280, university: 1920, professional: 2400 },
  ],
};
