import type { SportConfig } from './types';

export const trackField: SportConfig = {
  id: 'track-field',
  name: 'Track & Field',
  emoji: '\u{1F3C3}',
  color: '#D946EF',
  courtType: 'track',
  positions: [
    {
      code: 'SPR', name: 'Sprinter', archetype: 'The Lightning Bolt', color: '#EF4444',
      goat: 'Usain Bolt', goatCountry: 'Jamaica',
      radarDimensions: [
        { key: 'top_speed', label: 'Top Speed', goatScore: 99 },
        { key: 'acceleration', label: 'Acceleration', goatScore: 97 },
        { key: 'reaction_time', label: 'Reaction Time', goatScore: 88 },
        { key: 'power', label: 'Explosive Power', goatScore: 99 },
        { key: 'stride_length', label: 'Stride Length', goatScore: 99 },
        { key: 'speed_endurance', label: 'Speed Endurance', goatScore: 95 },
        { key: 'technique', label: 'Running Form', goatScore: 93 },
        { key: 'clutch', label: 'Championship Composure', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 97 },
      ],
    },
    {
      code: 'DST', name: 'Distance Runner', archetype: 'The Endurance Machine', color: '#3B82F6',
      goat: 'Eliud Kipchoge', goatCountry: 'Kenya',
      radarDimensions: [
        { key: 'endurance', label: 'Endurance', goatScore: 99 },
        { key: 'pacing', label: 'Pacing', goatScore: 99 },
        { key: 'vo2_max', label: 'VO2 Max', goatScore: 97 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 99 },
        { key: 'kick', label: 'Finishing Kick', goatScore: 93 },
        { key: 'efficiency', label: 'Running Economy', goatScore: 99 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'race_tactics', label: 'Race Tactics', goatScore: 97 },
        { key: 'durability', label: 'Durability', goatScore: 98 },
        { key: 'discipline', label: 'Training Discipline', goatScore: 99 },
      ],
    },
    {
      code: 'JMP', name: 'Jumper', archetype: 'The Sky Walker', color: '#10B981',
      goat: 'Carl Lewis', goatCountry: 'USA',
      radarDimensions: [
        { key: 'explosiveness', label: 'Explosiveness', goatScore: 99 },
        { key: 'speed', label: 'Approach Speed', goatScore: 98 },
        { key: 'technique', label: 'Technique', goatScore: 96 },
        { key: 'coordination', label: 'Coordination', goatScore: 97 },
        { key: 'power', label: 'Leg Power', goatScore: 98 },
        { key: 'flexibility', label: 'Flexibility', goatScore: 90 },
        { key: 'consistency', label: 'Consistency', goatScore: 99 },
        { key: 'clutch', label: 'Championship Composure', goatScore: 97 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 96 },
        { key: 'durability', label: 'Durability', goatScore: 94 },
      ],
    },
    {
      code: 'THR', name: 'Thrower', archetype: 'The Titan', color: '#F59E0B',
      goat: 'Jan Zelezny', goatCountry: 'Czech Republic',
      radarDimensions: [
        { key: 'power', label: 'Raw Power', goatScore: 99 },
        { key: 'technique', label: 'Technique', goatScore: 99 },
        { key: 'speed', label: 'Rotational Speed', goatScore: 96 },
        { key: 'coordination', label: 'Coordination', goatScore: 97 },
        { key: 'strength', label: 'Strength', goatScore: 98 },
        { key: 'flexibility', label: 'Flexibility', goatScore: 92 },
        { key: 'release', label: 'Release Point', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 97 },
        { key: 'clutch', label: 'Championship Composure', goatScore: 96 },
        { key: 'mental_toughness', label: 'Mental Toughness', goatScore: 95 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'event', label: 'EVENT', type: 'text' },
    { key: 'result', label: 'RESULT', type: 'text' },
    { key: 'wind', label: 'WIND', type: 'text' },
    { key: 'place', label: 'PL', type: 'number' },
    { key: 'round', label: 'RND', type: 'text' },
    { key: 'personal_best', label: 'PB', type: 'boolean' },
    { key: 'season_best', label: 'SB', type: 'boolean' },
    { key: 'points', label: 'PTS', type: 'number' },
    { key: 'reaction_time', label: 'RT', type: 'decimal' },
    { key: 'attempts', label: 'ATT', type: 'number' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '6-13', color: '#F59E0B',
      philosophy: 'Develop movement literacy through multi-event exposure. Run, jump, throw -- try everything.',
      keyFocus: ['Running form', 'Basic jumping', 'Throwing fundamentals', 'Fun and games'],
      restrictions: ['No specialization before 14 (Athletics Canada)', 'Modified implements', 'Multi-event focus'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '14-18', color: '#10B981',
      philosophy: 'Begin event specialization while maintaining multi-event base. Compete at OFSAA and club level.',
      keyFocus: ['Event specialization', 'Strength training intro', 'Competition skills', 'Technique refinement'],
      restrictions: ['Academic balance', 'Athletics Canada development pathway', 'OFSAA eligibility'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-23', color: '#3B82F6',
      philosophy: 'Compete at USports/NCAA level with full training programs and championship goals.',
      keyFocus: ['Advanced technique', 'Periodized training', 'Competition peaking', 'Sports science'],
      restrictions: ['USports/NCAA eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '18+', color: '#8B5CF6',
      philosophy: 'Chase world records, Olympic medals, and Diamond League titles.',
      keyFocus: ['Peak performance', 'Recovery science', 'Biomechanical optimization', 'Mental performance'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    SPR: [
      { name: 'The Lightning Bolt', description: 'Fastest human on the track who wins with pure top-end speed', traits: ['Top speed', 'Stride length', 'Power'] },
      { name: 'The Starter', description: 'Explosive out of the blocks and leads from the gun', traits: ['Reaction time', 'Acceleration', 'Drive phase'] },
      { name: 'The Bend Runner', description: 'Dominates the 200m and 400m with bend technique', traits: ['Bend running', 'Speed endurance', 'Lean'] },
      { name: 'The Relay Specialist', description: 'Master of baton exchanges and team speed events', traits: ['Exchange timing', 'Acceleration', 'Communication'] },
    ],
    DST: [
      { name: 'The Endurance Machine', description: 'Maintains pace that breaks rivals over long distances', traits: ['Endurance', 'Pacing', 'Economy'] },
      { name: 'The Kicker', description: 'Tactically patient runner who out-sprints the field at the end', traits: ['Finishing kick', 'Tactics', 'Speed'] },
      { name: 'The Front Runner', description: 'Sets a brutal pace from the start and dares others to follow', traits: ['Courage', 'Strength', 'Pacing'] },
      { name: 'The Marathoner', description: 'Built for the longest distances with unbreakable mental strength', traits: ['Mental toughness', 'Efficiency', 'Durability'] },
    ],
    JMP: [
      { name: 'The Sky Walker', description: 'Soars through the air with incredible hang time', traits: ['Explosiveness', 'Air time', 'Power'] },
      { name: 'The Technician', description: 'Perfect form on every attempt with minimal fouls', traits: ['Technique', 'Consistency', 'Precision'] },
      { name: 'The Speed Jumper', description: 'Converts elite sprint speed into massive jumps', traits: ['Speed', 'Approach', 'Conversion'] },
      { name: 'The Big-Stage Performer', description: 'Saves the best for championship finals', traits: ['Clutch', 'Composure', 'Peak performance'] },
    ],
    THR: [
      { name: 'The Titan', description: 'Pure power athlete who launches implements to world-class distances', traits: ['Power', 'Strength', 'Force production'] },
      { name: 'The Technician', description: 'Maximizes distance through flawless throwing mechanics', traits: ['Technique', 'Release angle', 'Timing'] },
      { name: 'The Speed Thrower', description: 'Generates elite rotational or approach velocity', traits: ['Speed', 'Rotational power', 'Quickness'] },
      { name: 'The Competitor', description: 'Elevates performance when it matters most in competition', traits: ['Clutch', 'Composure', 'Aggression'] },
    ],
  },
  personaQuiz: [
    {
      question: 'It\'s the Olympic final. What do you want to be doing?',
      options: [
        { text: 'Blazing down the straight to the finish line', archetypes: { SPR: 'The Lightning Bolt', DST: 'The Kicker', JMP: 'The Speed Jumper', THR: 'The Speed Thrower' } },
        { text: 'Grinding through the pain to outlast everyone', archetypes: { SPR: 'The Bend Runner', DST: 'The Endurance Machine', JMP: 'The Big-Stage Performer', THR: 'The Competitor' } },
        { text: 'Nailing the perfect technique for a record', archetypes: { SPR: 'The Starter', DST: 'The Front Runner', JMP: 'The Technician', THR: 'The Technician' } },
        { text: 'Launching something as far as humanly possible', archetypes: { SPR: 'The Relay Specialist', DST: 'The Marathoner', JMP: 'The Sky Walker', THR: 'The Titan' } },
      ],
    },
    {
      question: 'What part of training do you enjoy most?',
      options: [
        { text: 'Speed work and sprints', archetypes: { SPR: 'The Lightning Bolt', DST: 'The Kicker', JMP: 'The Speed Jumper', THR: 'The Speed Thrower' } },
        { text: 'Long runs and tempo work', archetypes: { SPR: 'The Bend Runner', DST: 'The Endurance Machine', JMP: 'The Big-Stage Performer', THR: 'The Competitor' } },
        { text: 'Technical drills and video review', archetypes: { SPR: 'The Starter', DST: 'The Front Runner', JMP: 'The Technician', THR: 'The Technician' } },
        { text: 'Weight room and plyometrics', archetypes: { SPR: 'The Relay Specialist', DST: 'The Marathoner', JMP: 'The Sky Walker', THR: 'The Titan' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The fastest athlete they\'ve ever coached', archetypes: { SPR: 'The Lightning Bolt', DST: 'The Kicker', JMP: 'The Speed Jumper', THR: 'The Speed Thrower' } },
        { text: 'The toughest competitor on the team', archetypes: { SPR: 'The Bend Runner', DST: 'The Endurance Machine', JMP: 'The Big-Stage Performer', THR: 'The Competitor' } },
        { text: 'The most technically sound athlete', archetypes: { SPR: 'The Starter', DST: 'The Front Runner', JMP: 'The Technician', THR: 'The Technician' } },
        { text: 'The most powerful athlete on the roster', archetypes: { SPR: 'The Relay Specialist', DST: 'The Marathoner', JMP: 'The Sky Walker', THR: 'The Titan' } },
      ],
    },
    {
      question: 'What matters most to you in competition?',
      options: [
        { text: 'Winning the race or event', archetypes: { SPR: 'The Lightning Bolt', DST: 'The Kicker', JMP: 'The Speed Jumper', THR: 'The Speed Thrower' } },
        { text: 'Setting a personal best', archetypes: { SPR: 'The Starter', DST: 'The Endurance Machine', JMP: 'The Technician', THR: 'The Technician' } },
        { text: 'Performing well under pressure', archetypes: { SPR: 'The Bend Runner', DST: 'The Front Runner', JMP: 'The Big-Stage Performer', THR: 'The Competitor' } },
        { text: 'Breaking records', archetypes: { SPR: 'The Relay Specialist', DST: 'The Marathoner', JMP: 'The Sky Walker', THR: 'The Titan' } },
      ],
    },
  ],
  drills: [
    { name: 'Block Start Practice', position: 'SPR', difficulty: 3, description: 'React to starter commands and explode out of blocks for 30m', equipment: ['Starting blocks', 'Stopwatch'] },
    { name: 'Tempo Runs', position: 'DST', difficulty: 3, description: 'Run at 80% effort for 20-40 minutes to build aerobic base', equipment: ['Stopwatch', 'Track'] },
    { name: 'Approach Run Drills', position: 'JMP', difficulty: 4, description: 'Practice full approach runs hitting the board with consistent stride', equipment: ['Runway', 'Measuring tape'] },
    { name: 'Standing Throw Series', position: 'THR', difficulty: 3, description: 'Throw from a standing position focusing on release mechanics', equipment: ['Implement', 'Measuring tape'] },
    { name: 'Plyometric Circuit', position: 'ALL', difficulty: 3, description: 'Box jumps, bounding, and depth jumps for explosive power', equipment: ['Plyo boxes', 'Cones'] },
    { name: 'Sprint Relay Exchanges', position: 'SPR', difficulty: 4, description: 'Practice underhand and overhand baton exchanges at full speed', equipment: ['Batons', 'Cones', 'Track'] },
  ],
  benchmarks: [
    { name: '100m Time', unit: 'seconds', youth: 14.5, school: 12.0, university: 10.8, professional: 10.0 },
    { name: '1500m Time', unit: 'minutes', youth: 6.5, school: 4.8, university: 4.0, professional: 3.5 },
    { name: 'Standing Long Jump', unit: 'meters', youth: 1.5, school: 2.2, university: 2.8, professional: 3.3 },
    { name: 'Shot Put (4kg)', unit: 'meters', youth: 6, school: 11, university: 15, professional: 20 },
  ],
};
