import type { SportConfig } from './types';

export const volleyball: SportConfig = {
  id: 'volleyball',
  name: 'Volleyball',
  emoji: '\u{1F3D0}',
  color: '#FBBF24',
  courtType: 'court',
  positions: [
    {
      code: 'OH', name: 'Outside Hitter', archetype: 'The Terminator', color: '#EF4444',
      goat: 'Karch Kiraly', goatCountry: 'USA',
      radarDimensions: [
        { key: 'attacking', label: 'Attacking', goatScore: 98 },
        { key: 'serve_receive', label: 'Serve Receive', goatScore: 95 },
        { key: 'serving', label: 'Serving', goatScore: 92 },
        { key: 'blocking', label: 'Blocking', goatScore: 88 },
        { key: 'defense', label: 'Defense', goatScore: 94 },
        { key: 'court_awareness', label: 'Court Awareness', goatScore: 97 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
        { key: 'leadership', label: 'Leadership', goatScore: 98 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 97 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 95 },
      ],
    },
    {
      code: 'MB', name: 'Middle Blocker', archetype: 'The Wall', color: '#3B82F6',
      goat: 'Dmitriy Muserskiy', goatCountry: 'Russia',
      radarDimensions: [
        { key: 'blocking', label: 'Blocking', goatScore: 99 },
        { key: 'quick_attack', label: 'Quick Attack', goatScore: 96 },
        { key: 'read_blocking', label: 'Read Blocking', goatScore: 97 },
        { key: 'serving', label: 'Serving', goatScore: 88 },
        { key: 'footwork', label: 'Footwork', goatScore: 93 },
        { key: 'timing', label: 'Timing', goatScore: 98 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 95 },
        { key: 'court_awareness', label: 'Court Awareness', goatScore: 90 },
        { key: 'intimidation', label: 'Intimidation', goatScore: 96 },
        { key: 'consistency', label: 'Consistency', goatScore: 91 },
      ],
    },
    {
      code: 'RS', name: 'Right Side Hitter', archetype: 'The Opposite Force', color: '#10B981',
      goat: 'Wilfredo Leon', goatCountry: 'Poland',
      radarDimensions: [
        { key: 'attacking', label: 'Attacking', goatScore: 99 },
        { key: 'blocking', label: 'Blocking', goatScore: 93 },
        { key: 'serving', label: 'Serving', goatScore: 97 },
        { key: 'power', label: 'Power', goatScore: 99 },
        { key: 'shot_selection', label: 'Shot Selection', goatScore: 94 },
        { key: 'athleticism', label: 'Athleticism', goatScore: 98 },
        { key: 'back_row_attack', label: 'Back Row Attack', goatScore: 96 },
        { key: 'clutch', label: 'Clutch Factor', goatScore: 95 },
        { key: 'consistency', label: 'Consistency', goatScore: 92 },
        { key: 'court_awareness', label: 'Court Awareness', goatScore: 90 },
      ],
    },
    {
      code: 'SE', name: 'Setter', archetype: 'The Architect', color: '#F59E0B',
      goat: 'Bruno Rezende', goatCountry: 'Brazil',
      radarDimensions: [
        { key: 'setting', label: 'Setting Accuracy', goatScore: 99 },
        { key: 'court_vision', label: 'Court Vision', goatScore: 98 },
        { key: 'decision_making', label: 'Decision Making', goatScore: 97 },
        { key: 'serving', label: 'Serving', goatScore: 88 },
        { key: 'blocking', label: 'Blocking', goatScore: 82 },
        { key: 'dump_shot', label: 'Dump Shot', goatScore: 95 },
        { key: 'leadership', label: 'Leadership', goatScore: 99 },
        { key: 'tempo_control', label: 'Tempo Control', goatScore: 98 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
        { key: 'volleyball_iq', label: 'Volleyball IQ', goatScore: 99 },
      ],
    },
    {
      code: 'LI', name: 'Libero', archetype: 'The Shield', color: '#8B5CF6',
      goat: 'Sergio Dutra Santos', goatCountry: 'Brazil',
      radarDimensions: [
        { key: 'digging', label: 'Digging', goatScore: 99 },
        { key: 'serve_receive', label: 'Serve Receive', goatScore: 99 },
        { key: 'court_coverage', label: 'Court Coverage', goatScore: 98 },
        { key: 'reading', label: 'Reading the Hitter', goatScore: 97 },
        { key: 'reflexes', label: 'Reflexes', goatScore: 96 },
        { key: 'communication', label: 'Communication', goatScore: 98 },
        { key: 'passing', label: 'Passing Accuracy', goatScore: 98 },
        { key: 'agility', label: 'Agility', goatScore: 97 },
        { key: 'consistency', label: 'Consistency', goatScore: 96 },
        { key: 'volleyball_iq', label: 'Volleyball IQ', goatScore: 95 },
      ],
    },
  ],
  gameLogFields: [
    { key: 'kills', label: 'K', type: 'number' },
    { key: 'errors', label: 'E', type: 'number' },
    { key: 'attempts', label: 'ATT', type: 'number' },
    { key: 'aces', label: 'SA', type: 'number' },
    { key: 'blocks', label: 'BS', type: 'number' },
    { key: 'digs', label: 'DIG', type: 'number' },
    { key: 'assists', label: 'AST', type: 'number' },
    { key: 'sets', label: 'SET', type: 'number' },
    { key: 'serve_errors', label: 'SE', type: 'number' },
    { key: 'hit_pct', label: 'HIT%', type: 'percent' },
  ],
  stages: [
    {
      id: 'youth', label: 'Youth Explorer', ageRange: '8-13', color: '#F59E0B',
      philosophy: 'Develop love for the game through play, basic ball control, and movement patterns.',
      keyFocus: ['Passing fundamentals', 'Overhead setting', 'Movement patterns', 'Team play'],
      restrictions: ['Modified net heights', 'Smaller courts', 'Equal rotation time'],
    },
    {
      id: 'school', label: 'School Competitor', ageRange: '14-18', color: '#10B981',
      philosophy: 'Learn position-specific skills, compete in Volleyball Canada age-class and school leagues.',
      keyFocus: ['Position specialization', 'Serve & receive', 'Tactical systems', 'Jump training'],
      restrictions: ['Academic balance', 'Volleyball Canada age guidelines'],
    },
    {
      id: 'university', label: 'University Performer', ageRange: '18-23', color: '#3B82F6',
      philosophy: 'Compete at USports/NCAA level with advanced tactical and physical development.',
      keyFocus: ['Advanced system play', 'Video analysis', 'Strength & power', 'Mental performance'],
      restrictions: ['USports/NCAA eligibility', 'Academic requirements'],
    },
    {
      id: 'professional', label: 'Professional Elite', ageRange: '18+', color: '#8B5CF6',
      philosophy: 'Peak performance on the international stage and professional leagues worldwide.',
      keyFocus: ['Elite skill refinement', 'Recovery science', 'Tournament preparation', 'Leadership'],
      restrictions: [],
    },
  ],
  personaArchetypes: {
    OH: [
      { name: 'The Terminator', description: 'Go-to attacker who puts the ball away in crunch time', traits: ['Power', 'Aggression', 'Confidence'] },
      { name: 'The All-Around', description: 'Strong in every phase -- passing, hitting, and defense', traits: ['Versatility', 'Consistency', 'IQ'] },
      { name: 'The Shot Maker', description: 'Uses angles, tips, and placement over raw power', traits: ['Craft', 'Touch', 'Deception'] },
      { name: 'The Defender', description: 'Serve receive specialist who also contributes offensively', traits: ['Passing', 'Discipline', 'Court sense'] },
    ],
    MB: [
      { name: 'The Blocker', description: 'Dominant net presence who shuts down attacks', traits: ['Timing', 'Read ability', 'Reach'] },
      { name: 'The Quick Striker', description: 'Runs fast tempo attacks and slides', traits: ['Speed', 'Timing', 'Explosiveness'] },
      { name: 'The Intimidator', description: 'Imposes will at the net through sheer physical dominance', traits: ['Size', 'Power', 'Presence'] },
      { name: 'The Smart Middle', description: 'Reads the game and positions perfectly every time', traits: ['IQ', 'Anticipation', 'Footwork'] },
    ],
    RS: [
      { name: 'The Cannon', description: 'Overpowers blockers with sheer hitting velocity', traits: ['Power', 'Arm speed', 'Aggression'] },
      { name: 'The Complete Opposite', description: 'Elite at both attacking and blocking from the right', traits: ['Versatility', 'Blocking', 'Hitting'] },
      { name: 'The Serve Specialist', description: 'Weapon from the service line with jump serves', traits: ['Serve power', 'Accuracy', 'Consistency'] },
      { name: 'The Utility', description: 'Plugs into any system and contributes everywhere', traits: ['Adaptability', 'IQ', 'Reliability'] },
    ],
    SE: [
      { name: 'The Architect', description: 'Controls the offense and finds the hot hitter', traits: ['Vision', 'Decision making', 'Tempo'] },
      { name: 'The Aggressive Setter', description: 'Dumps, attacks second ball, and keeps defenses guessing', traits: ['Deception', 'Aggression', 'Scoring'] },
      { name: 'The Steadier', description: 'Consistent, reliable hands that never waver under pressure', traits: ['Consistency', 'Composure', 'Touch'] },
      { name: 'The Leader', description: 'Vocal floor general who commands the team', traits: ['Communication', 'Leadership', 'Presence'] },
    ],
    LI: [
      { name: 'The Shield', description: 'Nothing hits the floor -- elite dig and receive specialist', traits: ['Reflexes', 'Anticipation', 'Hustle'] },
      { name: 'The Passer', description: 'Perfect first contact that sets up the offense', traits: ['Platform', 'Footwork', 'Accuracy'] },
      { name: 'The Energizer', description: 'Brings intensity and fire to the back row every point', traits: ['Energy', 'Communication', 'Heart'] },
      { name: 'The Quarterback', description: 'Directs traffic and organizes the defense', traits: ['IQ', 'Communication', 'Leadership'] },
    ],
  },
  personaQuiz: [
    {
      question: 'It\'s match point against you. What do you want to do?',
      options: [
        { text: 'Put the ball away with a kill', archetypes: { OH: 'The Terminator', MB: 'The Quick Striker', RS: 'The Cannon', SE: 'The Aggressive Setter', LI: 'The Energizer' } },
        { text: 'Set up the best hitter for the swing', archetypes: { OH: 'The All-Around', MB: 'The Smart Middle', RS: 'The Utility', SE: 'The Architect', LI: 'The Quarterback' } },
        { text: 'Make the big dig to keep the rally alive', archetypes: { OH: 'The Defender', MB: 'The Blocker', RS: 'The Complete Opposite', SE: 'The Steadier', LI: 'The Shield' } },
        { text: 'Use smart placement to win the point', archetypes: { OH: 'The Shot Maker', MB: 'The Intimidator', RS: 'The Serve Specialist', SE: 'The Leader', LI: 'The Passer' } },
      ],
    },
    {
      question: 'What part of practice do you enjoy most?',
      options: [
        { text: 'Hitting lines', archetypes: { OH: 'The Terminator', MB: 'The Quick Striker', RS: 'The Cannon', SE: 'The Aggressive Setter', LI: 'The Energizer' } },
        { text: 'Running offensive plays', archetypes: { OH: 'The All-Around', MB: 'The Smart Middle', RS: 'The Utility', SE: 'The Architect', LI: 'The Quarterback' } },
        { text: 'Defensive and serve receive drills', archetypes: { OH: 'The Defender', MB: 'The Blocker', RS: 'The Complete Opposite', SE: 'The Steadier', LI: 'The Shield' } },
        { text: 'Serving practice', archetypes: { OH: 'The Shot Maker', MB: 'The Intimidator', RS: 'The Serve Specialist', SE: 'The Leader', LI: 'The Passer' } },
      ],
    },
    {
      question: 'Your coach describes you as:',
      options: [
        { text: 'The go-to player when we need a point', archetypes: { OH: 'The Terminator', MB: 'The Quick Striker', RS: 'The Cannon', SE: 'The Aggressive Setter', LI: 'The Energizer' } },
        { text: 'The brains of the team', archetypes: { OH: 'The All-Around', MB: 'The Smart Middle', RS: 'The Utility', SE: 'The Architect', LI: 'The Quarterback' } },
        { text: 'The most consistent player on the roster', archetypes: { OH: 'The Defender', MB: 'The Blocker', RS: 'The Complete Opposite', SE: 'The Steadier', LI: 'The Shield' } },
        { text: 'A player opponents don\'t want to face', archetypes: { OH: 'The Shot Maker', MB: 'The Intimidator', RS: 'The Serve Specialist', SE: 'The Leader', LI: 'The Passer' } },
      ],
    },
    {
      question: 'What stat matters most to you?',
      options: [
        { text: 'Kills', archetypes: { OH: 'The Terminator', MB: 'The Quick Striker', RS: 'The Cannon', SE: 'The Aggressive Setter', LI: 'The Energizer' } },
        { text: 'Assists', archetypes: { OH: 'The All-Around', MB: 'The Smart Middle', RS: 'The Utility', SE: 'The Architect', LI: 'The Quarterback' } },
        { text: 'Digs', archetypes: { OH: 'The Defender', MB: 'The Blocker', RS: 'The Complete Opposite', SE: 'The Steadier', LI: 'The Shield' } },
        { text: 'Aces', archetypes: { OH: 'The Shot Maker', MB: 'The Intimidator', RS: 'The Serve Specialist', SE: 'The Leader', LI: 'The Passer' } },
      ],
    },
  ],
  drills: [
    { name: 'Pepper', position: 'ALL', difficulty: 2, description: 'Partner drill alternating pass, set, hit in a controlled rally', equipment: ['Volleyball'] },
    { name: 'Serve Receive Triangle', position: 'LI', difficulty: 3, description: 'Receive serves to target from 3 court positions', equipment: ['Volleyball', 'Net'] },
    { name: 'Block-Transition Attack', position: 'MB', difficulty: 4, description: 'Block, land, transition off the net, and attack a set', equipment: ['Volleyball', 'Net'] },
    { name: 'Setter Decision Drill', position: 'SE', difficulty: 4, description: 'Run plays with 3 hitters reading live blockers', equipment: ['Volleyball', 'Net', 'Full team'] },
    { name: 'Cross-Court Hitting', position: 'OH', difficulty: 3, description: 'Hit sets to specific zones cross-court against a block', equipment: ['Volleyball', 'Net'] },
    { name: 'Jump Serve Accuracy', position: 'RS', difficulty: 4, description: 'Jump serve to marked target zones on the court', equipment: ['Volleyball', 'Net', 'Cones'] },
  ],
  benchmarks: [
    { name: 'Vertical Jump', unit: 'inches', youth: 14, school: 22, university: 28, professional: 35 },
    { name: 'Approach Jump', unit: 'inches', youth: 18, school: 26, university: 34, professional: 42 },
    { name: 'Agility T-Test', unit: 'seconds', youth: 12, school: 10.5, university: 9.5, professional: 8.5 },
    { name: 'Serve Speed', unit: 'km/h', youth: 40, school: 65, university: 85, professional: 110 },
  ],
};
